import json

import streamlit.components.v1 as components


SOLAR_COMPONENTS = {
  'component-pv-modules': {'id':'component-pv-modules','name':'PV Modules','category':'generation','overview':{'description':'PV modules convert sunlight into direct current electricity. At utility scale they define raw energy capture, so soiling, temperature, mismatch, and degradation immediately affect plant yield.','keyFunction':'Generate DC electricity from solar irradiance.','typicalSpec':'580-700 Wp bifacial modules, 1,500 VDC strings.'},'technical':{'voltage':'~35-45 VDC per module, up to 1,500 VDC per string.','current':'Typically 13-18 A short-circuit current per module.','powerRating':'580-700 Wp per module, aggregated to multi-MWdc blocks.','typicalManufacturers':['LONGi','Trina Solar','Jinko Solar','JA Solar'],'connectionUpstream':'Solar resource, tracker structure, earthing, and weather exposure.','connectionDownstream':'DC string cabling and combiner boxes or inverter inputs.','failureModes':['Hot spots','Cell cracking','PID or mismatch','Connector heating','Glass breakage']},'operations':{'inspectionFrequency':'Monthly visual checks plus annual thermography and IV investigations.','commonIssues':['Soiling','Bypass diode issues','Shading mismatch','Delamination','Accelerated degradation'],'performanceMetrics':['Specific yield','PR contribution','String current balance','Degradation rate'],'lifespanYears':'25-35 years','replacementCost':'Medium'},'scada':{'dataPoints':['String current','POA irradiance','Module temperature','Tracker angle'],'kpis':['Array availability','Mismatch loss','Soiling loss','Normalized energy'],'anomalySignals':['Persistent underperforming strings','Thermal outliers','PR drop in clear weather'],'scadaTags':['STR_CURR_*','POA_IRR','MOD_TEMP','ARRAY_AVAIL']}},
  'component-dc-cables': {'id':'component-dc-cables','name':'DC Cables','category':'transmission','overview':{'description':'DC cables collect energy from strings and route it to the combiner or inverter. Installation quality and connector integrity are critical because many latent faults appear first on the DC side.','keyFunction':'Carry string DC power to the aggregation point.','typicalSpec':'1.5 kV PV cable, commonly 4-10 mm2 for string circuits.'},'technical':{'voltage':'Designed for 1,500 VDC systems.','current':'String circuits commonly 13-18 A; higher on aggregated runs.','powerRating':'Rated by ampacity and voltage drop rather than by nameplate power.','typicalManufacturers':['Prysmian','Nexans','Lapp','Top Cable'],'connectionUpstream':'PV module strings.','connectionDownstream':'String combiners or direct inverter inputs.','failureModes':['Insulation damage','Loose connectors','Ground faults','Rodent damage','Reverse polarity wiring']},'operations':{'inspectionFrequency':'Quarterly visual route checks and annual thermal or continuity testing.','commonIssues':['Water ingress','Unsupported loops','Connector mismatch','Voltage drop issues'],'performanceMetrics':['Circuit availability','Ground fault rate','Voltage consistency'],'lifespanYears':'20-30 years','replacementCost':'Low to medium'},'scada':{'dataPoints':['String voltage','String current','Insulation alarms'],'kpis':['DC availability','Current dispersion','Fault recurrence'],'anomalySignals':['Intermittent string loss','Insulation alarms','Large current mismatch'],'scadaTags':['DC_VOLT_*','DC_CURR_*','GROUND_FAULT']}},
  'component-string-combiner': {'id':'component-string-combiner','name':'String Combiner Boxes','category':'protection','overview':{'description':'Combiner boxes merge multiple strings onto fewer outgoing feeders and provide DC fusing, surge protection, and often string-level monitoring. They are a practical isolation point when string behavior diverges.','keyFunction':'Aggregate strings and provide DC protection and monitoring.','typicalSpec':'8-32 inputs, fused, with SPD and monitored output.'},'technical':{'voltage':'1,000-1,500 VDC.','current':'Often 150-400 A aggregated output depending on the block.','powerRating':'Tied to the number of strings feeding each inverter block.','typicalManufacturers':['Weidmuller','Phoenix Contact','Eaton','Mersen'],'connectionUpstream':'Individual PV string circuits.','connectionDownstream':'Main DC feeders to inverter MPPT inputs.','failureModes':['Fuse operation','SPD end-of-life','Water ingress','Loose terminations']},'operations':{'inspectionFrequency':'Quarterly visual checks and annual torque and thermal verification.','commonIssues':['Blown fuses','SPD alarms','Burnt terminals','Seal failure'],'performanceMetrics':['Healthy string count','Current balance','SPD status'],'lifespanYears':'15-25 years','replacementCost':'Medium'},'scada':{'dataPoints':['Per-string current','Output current','Fuse status','SPD status'],'kpis':['Strings online','Mismatch index','Fault isolation speed'],'anomalySignals':['Single-string collapse','Repeated fuse trips','Combiner undercurrent'],'scadaTags':['SCB_STR_CURR_*','SCB_OUT_CURR','SCB_FUSE_ALM']}},
  'component-inverter': {'id':'component-inverter','name':'String / Central Inverter','category':'conversion','overview':{'description':'The inverter converts variable DC from the field into synchronized AC power while performing MPPT, protection, and grid-support functions. It is one of the highest-leverage components in terms of both availability and performance.','keyFunction':'Convert DC to grid-compliant AC power.','typicalSpec':'150-350 kW string inverter or 2.5-5 MW central inverter, 98.5%+ peak efficiency.'},'technical':{'voltage':'DC up to 1,500 V; AC output typically 400-800 VAC.','current':'Usually hundreds of amps on the LV AC side depending on unit size.','powerRating':'From 150 kW string units to 5 MW+ central units.','typicalManufacturers':['Sungrow','Huawei','Power Electronics','SMA'],'connectionUpstream':'Combiner outputs or direct strings.','connectionDownstream':'LV AC feeders to the step-up transformer.','failureModes':['Power stack failure','Fan/filter degradation','Control board faults','Grid trips']},'operations':{'inspectionFrequency':'Daily remote review and semi-annual or annual preventive maintenance.','commonIssues':['Thermal derating','Repeated trips','Firmware issues','Auxiliary power loss'],'performanceMetrics':['Availability','Efficiency','Trip rate','MPPT balance','Clipping hours'],'lifespanYears':'10-15 years','replacementCost':'High'},'scada':{'dataPoints':['DC V/I','AC active/reactive power','Temperature','Alarm codes','Status'],'kpis':['Availability','Efficiency','Specific yield by block','Reactive compliance'],'anomalySignals':['Frequent trip-reset cycles','Persistent underproduction','Temperature-driven derating'],'scadaTags':['INV_P_AC','INV_Q_AC','INV_DC_V','INV_DC_I','INV_ALARM_CODE']}},
  'component-ac-cables-lv': {'id':'component-ac-cables-lv','name':'LV/MV AC Cables','category':'transmission','overview':{'description':'These feeders transfer inverter output to the local step-up transformer. Proper sizing, harmonic duty, and installation discipline matter because small weaknesses can become repeated breaker or thermal issues.','keyFunction':'Carry inverter AC power to the transformer.','typicalSpec':'400-800 VAC feeders sized for thermal and harmonic duty.'},'technical':{'voltage':'Typically 400-800 VAC.','current':'Several hundred amps depending on inverter rating.','powerRating':'Aligned to inverter block power and transformer LV side rating.','typicalManufacturers':['Nexans','Prysmian','General Cable','Top Cable'],'connectionUpstream':'Inverter AC terminals.','connectionDownstream':'MV transformer low-voltage side.','failureModes':['Loose lugs','Insulation breakdown','Joint defects','Water ingress']},'operations':{'inspectionFrequency':'Semi-annual visual and thermal checks plus outage testing as required.','commonIssues':['Hot joints','Phase imbalance','Sheath damage','Incorrect phase rotation'],'performanceMetrics':['Cable loss','Thermal margin','Fault incidence'],'lifespanYears':'20-30 years','replacementCost':'Medium'},'scada':{'dataPoints':['Phase current','Phase voltage','Feeder status'],'kpis':['Phase balance','Cable loading','Loss factor'],'anomalySignals':['Breaker trips','Current asymmetry','Unexpected transformer inlet heating'],'scadaTags':['LV_I_A','LV_I_B','LV_I_C','LV_FEEDER_STATUS']}},
  'component-mv-transformer': {'id':'component-mv-transformer','name':'MV Step-Up Transformer','category':'conversion','overview':{'description':'The block transformer raises inverter output from low voltage to the plant\'s medium-voltage collection network. It is the electrical bridge between conversion equipment and the export path.','keyFunction':'Step LV inverter output up to plant MV level.','typicalSpec':'0.4-0.8 kV to 20-33 kV, usually 2.5-8 MVA.'},'technical':{'voltage':'Typical ratio 690 VAC / 33 kV or similar.','current':'High current on LV, lower current on MV; rated in MVA.','powerRating':'2.5-8 MVA per transformer block.','typicalManufacturers':['Hitachi Energy','Schneider Electric','Siemens Energy','TMC'],'connectionUpstream':'Inverter LV output.','connectionDownstream':'MV switchgear and feeder cable.','failureModes':['Oil leaks','Winding insulation degradation','Bushing failure','Thermal overload']},'operations':{'inspectionFrequency':'Monthly visual checks with annual oil and electrical testing.','commonIssues':['Hot oil alarms','Cooling failures','Leaking gaskets','Protection trips'],'performanceMetrics':['Loading','Top oil temp','Winding temp','Availability'],'lifespanYears':'25-35 years','replacementCost':'High'},'scada':{'dataPoints':['Oil temp','Winding temp','Currents','Protection status'],'kpis':['Loading factor','Thermal aging index','Trip frequency'],'anomalySignals':['Rising temperature at constant load','Gas alarms','Unbalanced current'],'scadaTags':['XFMR_TOP_OIL_TEMP','XFMR_WDG_TEMP','XFMR_MVA','XFMR_TRIP']}},
  'component-mv-switchgear': {'id':'component-mv-switchgear','name':'MV Switchgear','category':'protection','overview':{'description':'MV switchgear provides switching, isolation, and protection between PV feeder transformers, the BESS branch, and the collection bus. It is the operational control point used to sectionalize faults and manage outages.','keyFunction':'Switch and protect the MV feeders and shared bus.','typicalSpec':'20-33 kV switchgear with vacuum breakers and protection relays.'},'technical':{'voltage':'20-33 kV collection bus.','current':'Common feeder ratings 630-2,500 A.','powerRating':'Rated by voltage, current, and fault duty.','typicalManufacturers':['Schneider Electric','ABB','Siemens','Ormazabal'],'connectionUpstream':'PV and BESS feeder transformers.','connectionDownstream':'MV collection network and substation bus.','failureModes':['Breaker mechanism failure','Relay misoperation','Arc damage','Interlock faults']},'operations':{'inspectionFrequency':'Monthly checks with periodic relay and breaker maintenance.','commonIssues':['Loss of control power','Stored-energy wear','Door interlock defects'],'performanceMetrics':['Feeder uptime','Breaker operation count','Fault clearing time'],'lifespanYears':'20-30 years','replacementCost':'High'},'scada':{'dataPoints':['Breaker status','Trip cause','Bus voltage','Feeder current'],'kpis':['Protection availability','Selectivity success','Breaker health'],'anomalySignals':['Repeat feeder trips','Slow operations','Protection alarms without obvious external fault'],'scadaTags':['MV_BRK_STATUS','MV_TRIP_CAUSE','MV_BUS_V','MV_FEEDER_I']}},
  'component-mv-cables': {'id':'component-mv-cables','name':'MV Collection Cables','category':'transmission','overview':{'description':'The MV collection network moves aggregated feeder power to the substation. Because it is usually underground, failures are less visible and often more disruptive to isolate and repair.','keyFunction':'Carry MV power from distributed blocks to the substation.','typicalSpec':'12-36 kV XLPE underground collection circuits.'},'technical':{'voltage':'Commonly 20-33 kV.','current':'Depends on feeder aggregation and soil thermal conditions.','powerRating':'Driven by conductor size and feeder topology.','typicalManufacturers':['Prysmian','Nexans','NKT','Elsewedy'],'connectionUpstream':'MV switchgear outgoing feeders.','connectionDownstream':'Substation incomers.','failureModes':['Joint failure','Insulation puncture','Sheath damage','Water treeing']},'operations':{'inspectionFrequency':'Route checks after civils and periodic testing during outages.','commonIssues':['Joint overheating','Moisture ingress','Damaged route marking'],'performanceMetrics':['Feeder losses','Fault rate per km','Cable health index'],'lifespanYears':'25-40 years','replacementCost':'High'},'scada':{'dataPoints':['Feeder current','Voltage drop','Fault indications'],'kpis':['Network availability','Loss factor','Fault localization time'],'anomalySignals':['Unexplained feeder trips','Voltage depression','Intermittent insulation alarms'],'scadaTags':['MV_FEEDER_LOAD','MV_ROUTE_FAULT','MV_VDROP']}},
  'component-hv-transformer': {'id':'component-hv-transformer','name':'HV Main Transformer','category':'conversion','overview':{'description':'The main transformer raises plant MV to the utility export voltage and is a central high-value asset. All export typically passes through it before reaching the point of common coupling.','keyFunction':'Step plant MV up to HV export level.','typicalSpec':'20-33 kV to 63-225 kV, tens to hundreds of MVA.'},'technical':{'voltage':'Primary 20-33 kV; secondary often 63, 90, 132, or 225 kV.','current':'Rated in MVA with lower current on the HV side.','powerRating':'Typically 40-250 MVA.','typicalManufacturers':['Hitachi Energy','GE Vernova','Siemens Energy','Hyosung'],'connectionUpstream':'MV switchgear or substation MV bus.','connectionDownstream':'HV yard and PCC.','failureModes':['Insulation aging','Cooling failure','Bushing flashover','Differential trips']},'operations':{'inspectionFrequency':'Continuous remote supervision with annual DGA and electrical tests.','commonIssues':['Cooling bank outages','Oil seepage','Contaminated bushings','Abnormal DGA'],'performanceMetrics':['Export availability','Thermal loading','DGA trend health'],'lifespanYears':'30-40 years','replacementCost':'High'},'scada':{'dataPoints':['Oil temp','Winding temp','Tap position','Currents','Protection states'],'kpis':['Availability','Thermal aging rate','Forced outage risk'],'anomalySignals':['Rising gas content','Unexpected tap movement','Top-oil rise without load increase'],'scadaTags':['GSU_TOP_OIL','GSU_WDG_TEMP','GSU_TAP_POS','GSU_DIFF_TRIP']}},
  'component-substation': {'id':'component-substation','name':'HV Substation','category':'transmission','overview':{'description':'The substation consolidates transformation, protection, metering, control, and switching before export. It is the place where plant electrical behavior becomes visible to the utility operator.','keyFunction':'Host the export bus, switching, metering, and grid interface controls.','typicalSpec':'AIS or GIS yard with utility relays, station auxiliaries, and telecontrol.'},'technical':{'voltage':'Matches the utility connection level and the plant MV level internally.','current':'Defined by plant export capacity and fault studies.','powerRating':'Full plant export capability plus duty margin.','typicalManufacturers':['Hitachi Energy','Schneider Electric','Siemens Energy','GE Vernova'],'connectionUpstream':'MV collection system and main transformer.','connectionDownstream':'Transmission or distribution utility line.','failureModes':['Auxiliary supply failure','Breaker defects','Protection miscoordination','Metering chain faults']},'operations':{'inspectionFrequency':'Daily remote supervision and periodic yard and relay maintenance.','commonIssues':['Battery charger alarms','Protection comms loss','Yard contamination'],'performanceMetrics':['Export availability','Compliance events','Breaker operations'],'lifespanYears':'30+ years','replacementCost':'High'},'scada':{'dataPoints':['Bus voltage','Export current','Breaker positions','Relay events'],'kpis':['Substation availability','Trip cause resolution time','Compliance'],'anomalySignals':['Unexpected protection blocks','Telemetry loss to grid operator','Repeated breaker alarms'],'scadaTags':['SUB_BUS_V','SUB_EXPORT_MW','SUB_BREAKER_STATUS','SUB_RELAY_EVENT']}},
  'component-grid-connection': {'id':'component-grid-connection','name':'Grid Connection Point (PCC)','category':'transmission','overview':{'description':'The PCC is the contractual and electrical interface between the plant and the public grid. Revenue metering and grid-code compliance are anchored here.','keyFunction':'Define the export interface with the utility network.','typicalSpec':'Revenue metering, power quality supervision, intertrip and dispatch interface.'},'technical':{'voltage':'Same as utility interconnection level.','current':'Driven by export capacity and network conditions.','powerRating':'Full contracted import/export capability.','typicalManufacturers':['Landis+Gyr','Schneider Electric','Siemens','Secure Meters'],'connectionUpstream':'HV substation outgoing bay.','connectionDownstream':'Utility feeder or transmission line.','failureModes':['Meter discrepancy','Power quality non-compliance','Dispatch signal loss']},'operations':{'inspectionFrequency':'Continuous supervision with periodic calibration and utility witness testing.','commonIssues':['Reactive power non-compliance','Curtailment mismatch','Meter communications faults'],'performanceMetrics':['Export MWh','Availability at PCC','Reactive compliance'],'lifespanYears':'20-30 years','replacementCost':'Medium to high'},'scada':{'dataPoints':['Revenue energy','P/Q export','Voltage','Frequency','Curtailment setpoint'],'kpis':['Grid code compliance','Curtailment impact','Export availability'],'anomalySignals':['Mismatch between plant and revenue meter','Unexpected clipping or curtailment','Frequency excursions'],'scadaTags':['PCC_MW','PCC_MVAR','PCC_KWH','PCC_FREQ','CURTAIL_SETPOINT']}},
  'component-bess-batteries': {'id':'component-bess-batteries','name':'BESS Battery Racks','category':'storage','overview':{'description':'Battery racks store energy for shifting, ramp control, and ancillary services. Their state of health and thermal behavior determine how much usable energy remains available over time.','keyFunction':'Store electrical energy for later dispatch.','typicalSpec':'Containerized LFP or NMC systems, 3.2-3.7 V per cell, hundreds of kWh per rack string.'},'technical':{'voltage':'Cell 3.2-3.7 V; container bus often 700-1,500 VDC.','current':'High bidirectional DC current depending on C-rate.','powerRating':'Typically paired to 1-4 hour system duration at MW scale.','typicalManufacturers':['CATL','BYD','Tesla','Fluence'],'connectionUpstream':'BMS, HVAC, fire suppression, and DC battery bus.','connectionDownstream':'PCS DC inputs.','failureModes':['Cell imbalance','Cooling failure','SOC drift','Thermal runaway precursor alarms']},'operations':{'inspectionFrequency':'Continuous BMS monitoring with monthly physical inspections.','commonIssues':['Rack imbalance','HVAC faults','Reduced usable energy','BMS comms loss'],'performanceMetrics':['SOC','SOH','Round-trip efficiency','Cycle count','Temperature spread'],'lifespanYears':'10-20 years','replacementCost':'High'},'scada':{'dataPoints':['SOC','SOH','Cell temperatures','Rack voltage','BMS alarms'],'kpis':['Available energy','Cycle count','Thermal uniformity','Degradation rate'],'anomalySignals':['Diverging rack voltages','Fast temperature rise','Repeated HVAC alarms'],'scadaTags':['BESS_SOC','BESS_SOH','BESS_CELL_TEMP_MAX','BMS_ALARM_CODE']}},
  'component-bess-pcs': {'id':'component-bess-pcs','name':'BESS Power Conversion System (PCS)','category':'conversion','overview':{'description':'The PCS is the bidirectional inverter that charges and discharges the battery system while supporting voltage and reactive power control. It converts stored energy into dispatchable AC power.','keyFunction':'Convert battery DC to AC and AC back to DC under dispatch control.','typicalSpec':'1-5 MW bidirectional converter with four-quadrant capability.'},'technical':{'voltage':'DC bus often 900-1,500 V; AC side typically 400-690 VAC.','current':'High bidirectional current on both DC and AC interfaces.','powerRating':'1-5 MW per PCS block is common.','typicalManufacturers':['Sungrow','Power Electronics','SMA','Gamesa Electric'],'connectionUpstream':'Battery racks and DC bus.','connectionDownstream':'BESS transformer and MV switchgear.','failureModes':['Power electronics failure','Cooling derating','Control instability','Grid-code trips']},'operations':{'inspectionFrequency':'Daily remote review and annual OEM maintenance.','commonIssues':['Missed dispatch setpoints','Harmonic alarms','Cooling issues','EMS comms mismatch'],'performanceMetrics':['Availability','Response time','Efficiency','Command tracking error'],'lifespanYears':'10-15 years','replacementCost':'High'},'scada':{'dataPoints':['Charge/discharge MW','Reactive power','DC V/I','Alarm codes','Dispatch mode'],'kpis':['Response latency','Conversion efficiency','Availability'],'anomalySignals':['Unexpected idle state','Grid faults','High harmonic alarms','Missed commands'],'scadaTags':['PCS_P_CMD','PCS_P_ACT','PCS_Q_ACT','PCS_MODE','PCS_ALARM']}},
  'component-bess-transformer': {'id':'component-bess-transformer','name':'BESS Transformer','category':'conversion','overview':{'description':'The BESS transformer steps the PCS output to the shared MV bus. It lets storage connect to the same collection architecture as the PV field while remaining operationally distinct.','keyFunction':'Step PCS output to the plant MV collection voltage.','typicalSpec':'0.4-0.69 kV to 20-33 kV, sized to PCS block rating.'},'technical':{'voltage':'Typically 400-690 VAC / 20-33 kV.','current':'Bidirectional thermal duty driven by dispatch cycles.','powerRating':'1-5 MVA per PCS block.','typicalManufacturers':['Hitachi Energy','Schneider Electric','TMC','Efacec'],'connectionUpstream':'PCS output panel.','connectionDownstream':'MV switchgear shared with PV collection.','failureModes':['Thermal overload','Insulation wear','Cooling issues','Protection trips']},'operations':{'inspectionFrequency':'Monthly visual checks and annual electrical testing.','commonIssues':['Thermal cycling stress','Cooling fan faults','Loose connections'],'performanceMetrics':['Loading profile','Temperature profile','Availability'],'lifespanYears':'20-30 years','replacementCost':'High'},'scada':{'dataPoints':['Temperature','Current','Protection status','Cooling alarms'],'kpis':['BESS export path availability','Thermal stress','Trip frequency'],'anomalySignals':['High temperature at moderate dispatch','Overcurrent relay events'],'scadaTags':['BESS_XFMR_TEMP','BESS_XFMR_I','BESS_XFMR_TRIP']}},
  'component-monitoring-scada': {'id':'component-monitoring-scada','name':'SCADA / Monitoring System','category':'monitoring','overview':{'description':'The SCADA layer acquires data, stores events, distributes alarms, and gives operators a unified view of the plant. It turns dispersed equipment behavior into actionable operational decisions.','keyFunction':'Centralize monitoring, alarming, dispatch, and reporting.','typicalSpec':'Plant historian, gateway, PLC/RTU, OEM interfaces, and remote dashboards.'},'technical':{'voltage':'Low-voltage controls and communication infrastructure.','current':'Not power-critical; driven by auxiliaries and network devices.','powerRating':'Usually station auxiliary loads only.','typicalManufacturers':['Power Factors','Meteocontrol','Schneider Electric','Siemens'],'connectionUpstream':'Field devices, relays, meters, weather stations, inverters, BMS/EMS.','connectionDownstream':'Operators, historians, analytics platforms, and utility telemetry.','failureModes':['Gateway outage','Time sync drift','Comms loss','Bad data mapping']},'operations':{'inspectionFrequency':'Continuous use with routine alarm rationalization and backup testing.','commonIssues':['Telemetry gaps','Tag scaling errors','Time offset','User access misconfiguration'],'performanceMetrics':['Data completeness','Alarm latency','System uptime'],'lifespanYears':'8-15 years','replacementCost':'Medium'},'scada':{'dataPoints':['All plant telemetry, statuses, alarms, events, setpoints'],'kpis':['Data quality','Alarm response time','Fleet availability'],'anomalySignals':['Frozen tags','Flatlined sensors','Clock drift','Communication loss'],'scadaTags':['SITE_MW','SITE_PR','COMM_HEALTH','ALARM_ACTIVE_COUNT']}},
  'component-weather-station': {'id':'component-weather-station','name':'Weather Station / Pyranometers','category':'monitoring','overview':{'description':'Weather stations provide the reference measurements needed to normalize plant output and diagnose underperformance. Without trusted irradiance and temperature data, PR and loss attribution become far less reliable.','keyFunction':'Measure irradiance and ambient conditions for performance assessment.','typicalSpec':'GHI and POA pyranometers, back-of-module temperature, wind speed and direction.'},'technical':{'voltage':'Low-voltage sensor and logger supply.','current':'Minimal instrumentation loads.','powerRating':'Instrumentation only.','typicalManufacturers':['Kipp & Zonen','Hukseflux','Vaisala','Campbell Scientific'],'connectionUpstream':'Meteorological exposure and mounting structures.','connectionDownstream':'SCADA historian, PPC, tracker control, and analytics.','failureModes':['Sensor drift','Soiling','Leveling errors','Heater failure','Cable damage']},'operations':{'inspectionFrequency':'Weekly cleanliness checks and periodic calibration.','commonIssues':['Dirty pyranometers','Tilt drift','Failed aspirated temperature probes'],'performanceMetrics':['Sensor availability','Calibration drift','Data plausibility'],'lifespanYears':'8-15 years','replacementCost':'Low to medium'},'scada':{'dataPoints':['GHI','POA','Ambient temperature','Module temperature','Wind speed'],'kpis':['Reference irradiance uptime','Clear-sky deviation','Sensor bias'],'anomalySignals':['Irradiance inconsistent with neighboring sensors','Flatlined temperature','Sudden offset after maintenance'],'scadaTags':['MET_GHI','MET_POA','MET_T_AMB','MET_T_MOD','MET_WIND']}},
  'component-tracker-system': {'id':'component-tracker-system','name':'Single-Axis Tracker System','category':'generation','overview':{'description':'Single-axis trackers rotate module tables to improve irradiance capture across the day while using backtracking to limit row-to-row shading. Their performance influences both energy yield and mechanical reliability.','keyFunction':'Orient PV rows to optimize irradiance capture and reduce shading losses.','typicalSpec':'Single-axis rows with motor drives, local controllers, and backtracking logic.'},'technical':{'voltage':'Typically low-voltage DC or AC motor supply.','current':'Driven by distributed tracker motors and controllers.','powerRating':'Auxiliary mechanical load rather than major electrical export equipment.','typicalManufacturers':['Nextracker','Array Technologies','PVHardware','GameChange Solar'],'connectionUpstream':'SCADA/PPC setpoints, weather conditions, site topography.','connectionDownstream':'PV module orientation and generation profile.','failureModes':['Stuck rows','Motor failures','Controller comms loss','Wind stow issues']},'operations':{'inspectionFrequency':'Weekly remote fault review and periodic mechanical inspection.','commonIssues':['Misalignment','Bearing wear','Limit switch issues','Backtracking misconfiguration'],'performanceMetrics':['Tracker availability','Stow response','Row angle accuracy'],'lifespanYears':'20-30 years','replacementCost':'Medium'},'scada':{'dataPoints':['Row angle','Mode','Wind stow status','Motor current','Fault code'],'kpis':['Tracker availability','Angle error','Stow event success'],'anomalySignals':['Persistent row angle offset','High motor current','Rows not returning from stow'],'scadaTags':['TRK_ANGLE','TRK_MODE','TRK_STOW','TRK_FAULT']}},
  'component-grounding-system': {'id':'component-grounding-system','name':'Grounding / Earthing System','category':'protection','overview':{'description':'The earthing system keeps touch and step voltages within safe limits and provides a fault return path for equipment protection. It also underpins lightning protection and EMC performance across the plant.','keyFunction':'Provide personnel safety, lightning protection, and fault current return paths.','typicalSpec':'Buried earth grid, equipment bonds, and lightning down conductors.'},'technical':{'voltage':'Designed around fault and lightning transients rather than steady-state voltage.','current':'Carries fault and surge currents for short durations.','powerRating':'Not rated by continuous export power.','typicalManufacturers':['nVent ERICO','OBO Bettermann','DEHN','Furse'],'connectionUpstream':'All metallic structures and electrical enclosures.','connectionDownstream':'Site earth grid, electrodes, and protective devices.','failureModes':['Corrosion','Broken bonds','High earth resistance','Lightning damage']},'operations':{'inspectionFrequency':'Annual inspection with periodic continuity and resistance testing.','commonIssues':['Loose bonds','Corroded lugs','Damaged lightning air terminals'],'performanceMetrics':['Earth resistance','Bond continuity','Lightning event inspections'],'lifespanYears':'25-40 years','replacementCost':'Low to medium'},'scada':{'dataPoints':['Insulation alarms','Ground fault alarms','Lightning counter pulses'],'kpis':['Ground fault incidence','Earthing test trend'],'anomalySignals':['Repeated insulation faults','Localized surge damage after storms'],'scadaTags':['GROUND_FAULT','INSULATION_ALARM','LIGHTNING_COUNT']}}
}


def render_solar_farm_explorer(site_name: str | None = None, height: int = 1700) -> None:
    title = site_name or 'Utility-Scale Solar PV + BESS Explorer'
    data = json.dumps(SOLAR_COMPONENTS)
    html = f"""
    <div id='sf-root'>
      <style>
        :root{{--bg:#FAFAF7;--ink:#2D2D2D;--navy:#1B2A4A;--copper:#D4864A;--green:#2E7D5B;--gold:#E8B84B;--muted:#8A9AAF;--line:#D7D9DE;--panel:#FFFDF9;--shadow:0 20px 40px rgba(27,42,74,.12);--radius:24px;--mono:'JetBrains Mono','IBM Plex Mono',Consolas,monospace;--serif:'DM Serif Display','Libre Baskerville',Georgia,serif;--sans:'Source Sans 3','DM Sans','Segoe UI',sans-serif;}}
        *{{box-sizing:border-box}} body{{margin:0;background:var(--bg);font-family:var(--sans);color:var(--ink)}}
        .shell{{display:flex;gap:24px;align-items:flex-start;padding:24px;background:var(--bg)}}
        .stage{{flex:1 1 60%;background:var(--panel);border:1px solid rgba(27,42,74,.08);border-radius:var(--radius);box-shadow:var(--shadow);padding:24px;min-width:0}}
        .panel{{flex:1 1 40%;position:sticky;top:16px;background:var(--panel);border:1px solid rgba(27,42,74,.08);border-radius:var(--radius);box-shadow:var(--shadow);padding:24px;min-height:720px}}
        .eyebrow{{letter-spacing:.18em;text-transform:uppercase;font-size:11px;color:var(--copper);font-weight:700;margin-bottom:8px}}
        h1,h2,h3{{font-family:var(--serif);margin:0}} h1{{font-size:32px;line-height:1.1;color:var(--navy)}} h2{{font-size:25px;color:var(--navy)}} h3{{font-size:17px;color:var(--navy)}}
        .lede{{color:#526070;max-width:68ch;font-size:16px;line-height:1.55;margin:14px 0 18px}}
        .controls{{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin-bottom:16px;padding:14px 16px;border-radius:18px;background:#F4F1EA;border:1px solid rgba(27,42,74,.08)}}
        .chip,.tab{{border:1px solid rgba(27,42,74,.12);background:#fff;border-radius:999px;padding:8px 12px;font:600 13px var(--sans);color:var(--navy)}}
        .tab.active{{background:var(--navy);color:#fff;border-color:var(--navy)}}
        .toggle{{border:none;background:var(--navy);color:#fff;border-radius:999px;padding:10px 14px;font:700 13px var(--sans);cursor:pointer;transition:background .24s ease,transform .24s ease}}
        .toggle.off{{background:#8A9AAF}} .toggle:hover{{transform:translateY(-1px)}}
        .metric{{margin-left:auto;display:flex;gap:10px;align-items:center;color:#5D687A;font-size:13px}} input[type=range]{{accent-color:var(--copper)}}
        .legend{{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0 0}} .legend span{{font-size:12px;color:#5F6C7C;padding:6px 10px;border-radius:999px;background:#F6F4EE;border:1px solid rgba(27,42,74,.08)}}
        svg{{width:100%;height:auto;border-radius:20px;background:#FFFDF8;border:1px solid rgba(27,42,74,.08)}}
        .node rect,.node path,.node circle,.node polygon,.node line,.node ellipse{{transition:fill .22s ease,stroke .22s ease,transform .22s ease,opacity .22s ease}}
        .node .body{{fill:#F6F1E9;stroke:#42526B;stroke-width:2.2}} .node .accent{{fill:#EBD8C5;stroke:#42526B;stroke-width:1.8}} .node text{{fill:#1B2A4A;font:600 20px var(--sans);pointer-events:none}}
        .node:hover .body,.node:hover .accent{{fill:#F1D9BF;cursor:pointer}} .node.selected .body,.node.selected .accent{{fill:#E8B84B;stroke:#D4864A}}
        .wire{{fill:none;stroke:#51627A;stroke-width:8;stroke-linecap:round;stroke-linejoin:round}} .dc{{stroke:#D4864A}} .ac{{stroke:#2E7D5B}} .aux{{stroke:#8A9AAF;stroke-dasharray:12 10;stroke-width:4}}
        .ground{{stroke:#6A4D39;stroke-width:5;fill:none}} .flow{{fill:none;stroke:#E8B84B;stroke-width:4;stroke-dasharray:2 16;stroke-linecap:round;opacity:.88;animation:dash var(--speed,6s) linear infinite}} .flow.reverse{{animation-direction:reverse}} .flow.off{{animation-play-state:paused;opacity:.18}}
        @keyframes dash{{from{{stroke-dashoffset:0}}to{{stroke-dashoffset:-260}}}}
        .panel.hidden .detail{{display:none}} .placeholder{{display:grid;place-items:center;height:100%;min-height:620px;color:#667588;text-align:left}}
        .pill{{display:inline-flex;align-items:center;gap:8px;background:#F5EFE8;color:var(--copper);border:1px solid rgba(212,134,74,.22);padding:7px 10px;border-radius:999px;font:700 11px var(--sans);letter-spacing:.12em;text-transform:uppercase}}
        .spec{{margin:18px 0 0;padding:16px;border-radius:18px;background:#F7F4EE;border:1px solid rgba(27,42,74,.08)}} .spec div{{font:600 13px var(--mono);color:#4B5970}}
        .tabs{{display:flex;flex-wrap:wrap;gap:8px;margin:18px 0}} .content p,.content li{{font-size:15px;line-height:1.6;color:#49596E}} .content ul{{padding-left:20px;margin:8px 0 0}}
        .kv{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:16px}} .card{{background:#F7F4EE;border:1px solid rgba(27,42,74,.08);border-radius:18px;padding:14px}} .card small{{display:block;color:#7A8798;text-transform:uppercase;letter-spacing:.08em;font-size:11px;margin-bottom:8px}} .card strong{{display:block;color:#1B2A4A;font:700 15px var(--mono);line-height:1.45}}
        @media (max-width: 980px){{.shell{{flex-direction:column;padding:14px}} .panel{{position:relative;top:0;min-height:auto}} .metric{{margin-left:0;width:100%}} h1{{font-size:26px}} }}
      </style>
      <div class='shell'>
        <section class='stage'>
          <div class='eyebrow'>Interactive Asset Anatomy</div>
          <h1>{title}</h1>
          <p class='lede'>Explore the electrical architecture of a utility-scale PV plant with co-located battery storage. Click any asset in the one-line schematic to understand its function, technical envelope, O&amp;M priorities, and the SCADA signals that make it visible in operations.</p>
          <div class='controls'>
            <button id='flowToggle' class='toggle'>Animated Power Flow: On</button>
            <label class='chip'>Time-of-day loading <input id='flowRange' type='range' min='0' max='100' value='68'></label>
            <div class='metric'><span id='flowReadout'>Simulated export: 68%</span></div>
          </div>
          <svg viewBox='0 0 1480 840' role='img' aria-label='Solar farm one-line diagram'>
            <path class='wire dc' d='M220 208 C310 208 310 248 400 248'/> <path class='flow' data-flow='pv' d='M220 208 C310 208 310 248 400 248'/>
            <path class='wire dc' d='M520 248 C590 248 615 248 690 248'/> <path class='flow' data-flow='pv' d='M520 248 C590 248 615 248 690 248'/>
            <path class='wire ac' d='M808 248 C900 248 930 248 1005 248'/> <path class='flow' data-flow='pv' d='M808 248 C900 248 930 248 1005 248'/>
            <path class='wire ac' d='M1115 248 C1180 248 1195 248 1250 248'/> <path class='flow' data-flow='pv' d='M1115 248 C1180 248 1195 248 1250 248'/>
            <path class='wire ac' d='M1250 248 C1320 248 1320 248 1372 248'/> <path class='flow' data-flow='pv' d='M1250 248 C1320 248 1320 248 1372 248'/>
            <path class='wire ac' d='M1112 248 L1112 548 L1005 548'/> <path class='flow reverse' data-flow='bess' d='M1112 248 L1112 548 L1005 548'/>
            <path class='wire ac' d='M808 548 C890 548 918 548 1005 548'/> <path class='flow reverse' data-flow='bess' d='M808 548 C890 548 918 548 1005 548'/>
            <path class='wire dc' d='M520 548 C590 548 620 548 690 548'/> <path class='flow reverse' data-flow='bess' d='M520 548 C590 548 620 548 690 548'/>
            <path class='aux' d='M745 132 L745 72 L1280 72 L1280 164'/>
            <path class='aux' d='M248 160 L248 90 L745 90'/>
            <path class='aux' d='M250 618 L250 690 L745 690 L745 120'/>
            <path class='ground' d='M120 748 L1358 748'/>
            <path class='ground' d='M248 682 L248 748 M745 632 L745 748 M1112 598 L1112 748'/>
            <g id='component-pv-modules' class='node' data-component-type='generation' transform='translate(72 118)'><rect class='body' x='0' y='0' rx='24' ry='24' width='176' height='180'/><rect class='accent' x='22' y='28' rx='10' width='130' height='86'/><line class='accent' x1='55' y1='28' x2='55' y2='114'/><line class='accent' x1='88' y1='28' x2='88' y2='114'/><line class='accent' x1='121' y1='28' x2='121' y2='114'/><line class='accent' x1='22' y1='56' x2='152' y2='56'/><line class='accent' x1='22' y1='84' x2='152' y2='84'/><text x='22' y='146'>PV Modules</text><text x='22' y='168' style='font-size:14px;font-weight:500'>Bifacial strings at 1.5 kVDC</text></g>
            <g id='component-dc-cables' class='node' data-component-type='transmission' transform='translate(252 170)'><rect class='body' x='0' y='0' rx='22' width='148' height='78'/><path class='accent' d='M26 47 C48 27 58 57 78 37 C94 21 114 49 124 29'/><text x='20' y='34'>DC Cables</text><text x='20' y='56' style='font-size:13px;font-weight:500'>String &amp; homerun</text></g>
            <g id='component-string-combiner' class='node' data-component-type='protection' transform='translate(400 162)'><rect class='body' x='0' y='0' rx='22' width='120' height='108'/><rect class='accent' x='24' y='22' rx='8' width='72' height='36'/><line class='accent' x1='60' y1='58' x2='60' y2='86'/><line class='accent' x1='38' y1='84' x2='82' y2='84'/><text x='17' y='100' style='font-size:15px'>String Combiner</text></g>
            <g id='component-inverter' class='node' data-component-type='conversion' transform='translate(690 146)'><rect class='body' x='0' y='0' rx='24' width='118' height='146'/><rect class='accent' x='28' y='26' rx='8' width='62' height='44'/><path class='accent' d='M28 95 L45 79 L58 95 L72 79 L90 95'/><text x='19' y='120'>Inverter</text><text x='17' y='140' style='font-size:13px;font-weight:500'>DC to AC + MPPT</text></g>
            <g id='component-ac-cables-lv' class='node' data-component-type='transmission' transform='translate(842 190)'><rect class='body' x='0' y='0' rx='22' width='164' height='76'/><path class='accent' d='M24 38 L58 22 L92 38 L126 22'/><text x='19' y='34'>LV / MV AC Cables</text><text x='19' y='56' style='font-size:13px;font-weight:500'>Inverter feeders</text></g>
            <g id='component-mv-transformer' class='node' data-component-type='conversion' transform='translate(1006 156)'><rect class='body' x='0' y='0' rx='22' width='108' height='120'/><circle class='accent' cx='44' cy='54' r='16'/><circle class='accent' cx='68' cy='54' r='16'/><text x='18' y='96'>MV Step-Up</text><text x='18' y='115' style='font-size:13px;font-weight:500'>0.69 / 33 kV</text></g>
            <g id='component-mv-switchgear' class='node' data-component-type='protection' transform='translate(1160 182)'><rect class='body' x='0' y='0' rx='22' width='90' height='130'/><rect class='accent' x='26' y='24' rx='6' width='38' height='72'/><line class='accent' x1='45' y1='96' x2='45' y2='112'/><text x='14' y='126' style='font-size:13px'>MV Switchgear</text></g>
            <g id='component-mv-cables' class='node' data-component-type='transmission' transform='translate(1248 156)'><rect class='body' x='0' y='0' rx='22' width='124' height='76'/><path class='accent' d='M22 38 C40 18 52 56 72 34 C86 19 102 44 106 28'/><text x='19' y='34'>MV Cables</text><text x='19' y='56' style='font-size:13px;font-weight:500'>Collection network</text></g>
            <g id='component-hv-transformer' class='node' data-component-type='conversion' transform='translate(1148 330)'><rect class='body' x='0' y='0' rx='24' width='156' height='124'/><circle class='accent' cx='58' cy='56' r='22'/><circle class='accent' cx='92' cy='56' r='22'/><text x='24' y='100'>HV Transformer</text></g>
            <g id='component-substation' class='node' data-component-type='transmission' transform='translate(1298 332)'><rect class='body' x='0' y='0' rx='24' width='144' height='120'/><rect class='accent' x='22' y='28' rx='6' width='18' height='58'/><rect class='accent' x='62' y='18' rx='6' width='18' height='70'/><rect class='accent' x='102' y='34' rx='6' width='18' height='52'/><text x='23' y='104'>HV Substation</text></g>
            <g id='component-grid-connection' class='node' data-component-type='transmission' transform='translate(1324 170)'><rect class='body' x='0' y='0' rx='24' width='136' height='96'/><polygon class='accent' points='28,48 58,26 58,42 102,42 102,54 58,54 58,70'/><text x='18' y='84'>Grid Connection</text></g>
            <g id='component-bess-batteries' class='node' data-component-type='storage' transform='translate(210 470)'><rect class='body' x='0' y='0' rx='24' width='170' height='136'/><rect class='accent' x='24' y='28' rx='8' width='34' height='60'/><rect class='accent' x='68' y='28' rx='8' width='34' height='60'/><rect class='accent' x='112' y='28' rx='8' width='34' height='60'/><text x='23' y='112'>BESS Batteries</text></g>
            <g id='component-bess-pcs' class='node' data-component-type='conversion' transform='translate(690 468)'><rect class='body' x='0' y='0' rx='24' width='118' height='142'/><rect class='accent' x='26' y='22' rx='8' width='66' height='38'/><path class='accent' d='M30 92 L50 78 L64 92 L76 78 L90 92'/><text x='28' y='118'>BESS PCS</text><text x='17' y='138' style='font-size:13px;font-weight:500'>Bi-directional</text></g>
            <g id='component-bess-transformer' class='node' data-component-type='conversion' transform='translate(1004 470)'><rect class='body' x='0' y='0' rx='22' width='108' height='116'/><circle class='accent' cx='44' cy='52' r='15'/><circle class='accent' cx='68' cy='52' r='15'/><text x='18' y='94'>BESS XFMR</text></g>
            <g id='component-monitoring-scada' class='node' data-component-type='monitoring' transform='translate(640 20)'><rect class='body' x='0' y='0' rx='24' width='210' height='104'/><rect class='accent' x='24' y='22' rx='10' width='82' height='46'/><rect class='accent' x='118' y='22' rx='10' width='68' height='46'/><text x='22' y='84'>SCADA / Monitoring</text></g>
            <g id='component-weather-station' class='node' data-component-type='monitoring' transform='translate(118 24)'><rect class='body' x='0' y='0' rx='24' width='138' height='116'/><circle class='accent' cx='48' cy='42' r='14'/><line class='accent' x1='48' y1='56' x2='48' y2='88'/><line class='accent' x1='48' y1='88' x2='34' y2='102'/><line class='accent' x1='48' y1='88' x2='62' y2='102'/><text x='18' y='108' style='font-size:14px'>Weather Station</text></g>
            <g id='component-tracker-system' class='node' data-component-type='generation' transform='translate(60 596)'><rect class='body' x='0' y='0' rx='24' width='190' height='114'/><polygon class='accent' points='30,70 76,42 126,58 82,84'/><line class='accent' x1='94' y1='36' x2='116' y2='18'/><text x='22' y='102'>Tracker System</text></g>
            <g id='component-grounding-system' class='node' data-component-type='protection' transform='translate(658 706)'><rect class='body' x='0' y='0' rx='24' width='184' height='96'/><line class='accent' x1='92' y1='24' x2='92' y2='52'/><line class='accent' x1='60' y1='52' x2='124' y2='52'/><line class='accent' x1='68' y1='64' x2='116' y2='64'/><line class='accent' x1='76' y1='76' x2='108' y2='76'/><text x='24' y='36'>Grounding / Earthing</text><text x='24' y='60' style='font-size:13px;font-weight:500'>Safety + lightning path</text></g>
          </svg>
          <div class='legend'>
            <span>Generation</span><span>Conversion</span><span>Transmission</span><span>Storage</span><span>Monitoring</span><span>Protection</span>
          </div>
        </section>
        <aside id='panel' class='panel hidden'>
          <div class='placeholder' id='placeholder'>
            <div><div class='eyebrow'>Selection</div><h2>Choose a plant component</h2><p class='lede' style='margin-top:12px'>Click any highlighted asset on the schematic to inspect its purpose, operating envelope, failure signatures, and the SCADA context engineers rely on during performance reviews.</p></div>
          </div>
          <div class='detail' id='detail'></div>
        </aside>
      </div>
      <script>
        const data = {data};
        const root = document.getElementById('sf-root');
        const panel = root.querySelector('#panel');
        const detail = root.querySelector('#detail');
        const placeholder = root.querySelector('#placeholder');
        const tabs = ['overview','technical','operations','scada'];
        let currentId = null; let currentTab = 'overview'; let flowOn = true;
        const iconMap = {{generation:'Sun capture',conversion:'Power conversion',transmission:'Grid transfer',storage:'Energy storage',monitoring:'Monitoring',protection:'Protection'}};
        function list(items){{ return `<ul>${{(items||[]).map(x => `<li>${{x}}</li>`).join('')}}</ul>`; }}
        function sectionTab(c){{
          if(currentTab==='overview') return `<p>${{c.overview.description}}</p><div class='spec'><div>${{c.overview.keyFunction}}</div><div>${{c.overview.typicalSpec}}</div></div><div class='kv'><div class='card'><small>Category</small><strong>${{c.category}}</strong></div><div class='card'><small>Illustration</small><strong>${{iconMap[c.category]}}</strong></div></div>`;
          if(currentTab==='technical') return `<div class='kv'><div class='card'><small>Voltage</small><strong>${{c.technical.voltage}}</strong></div><div class='card'><small>Current / Rating</small><strong>${{c.technical.current}}</strong></div><div class='card'><small>Power Rating</small><strong>${{c.technical.powerRating}}</strong></div><div class='card'><small>Typical OEMs</small><strong>${{c.technical.typicalManufacturers.join(', ')}}</strong></div></div><p><strong>Upstream:</strong> ${{c.technical.connectionUpstream}}</p><p><strong>Downstream:</strong> ${{c.technical.connectionDownstream}}</p><h3>Failure Modes</h3>${{list(c.technical.failureModes)}}`;
          if(currentTab==='operations') return `<div class='kv'><div class='card'><small>Inspection Frequency</small><strong>${{c.operations.inspectionFrequency}}</strong></div><div class='card'><small>Lifecycle</small><strong>${{c.operations.lifespanYears}}</strong></div><div class='card'><small>Replacement Cost</small><strong>${{c.operations.replacementCost}}</strong></div><div class='card'><small>Core Metrics</small><strong>${{c.operations.performanceMetrics.join(', ')}}</strong></div></div><h3>Common Issues</h3>${{list(c.operations.commonIssues)}}`;
          return `<div class='kv'><div class='card'><small>Typical Data</small><strong>${{c.scada.dataPoints.join(', ')}}</strong></div><div class='card'><small>KPIs</small><strong>${{c.scada.kpis.join(', ')}}</strong></div></div><h3>Key SCADA Tags</h3>${{list(c.scada.scadaTags)}}<h3>Anomaly Signals</h3>${{list(c.scada.anomalySignals)}}`;
        }}
        function beep(freq){{ try{{ const ctx = new (window.AudioContext||window.webkitAudioContext)(); const osc = ctx.createOscillator(); const gain = ctx.createGain(); osc.type='sine'; osc.frequency.value=freq; gain.gain.value=.015; osc.connect(gain); gain.connect(ctx.destination); osc.start(); osc.stop(ctx.currentTime + .06); }}catch(e){{}} }}
        function renderPanel(){{
          if(!currentId){{ panel.classList.add('hidden'); placeholder.style.display='grid'; detail.innerHTML=''; return; }}
          const c = data[currentId]; panel.classList.remove('hidden'); placeholder.style.display='none';
          detail.innerHTML = `
            <div class='pill'>${{c.category}}</div>
            <h2 style='margin-top:14px'>${{c.name}}</h2>
            <p class='lede' style='margin:10px 0 0'>${{c.overview.description}}</p>
            <div class='tabs'>${{tabs.map(t => `<button class="tab ${{currentTab===t?'active':''}}" data-tab="${{t}}">${{t==='scada'?'Data & SCADA':t==='operations'?'O&M Considerations':t.charAt(0).toUpperCase()+t.slice(1)}}</button>`).join('')}}</div>
            <div class='content'>${{sectionTab(c)}}</div>`;
          detail.querySelectorAll('.tab').forEach(btn => btn.addEventListener('click', () => {{ currentTab = btn.dataset.tab; beep(620); renderPanel(); }}));
        }}
        root.querySelectorAll('.node').forEach(node => node.addEventListener('click', ev => {{ ev.stopPropagation(); root.querySelectorAll('.node').forEach(n => n.classList.remove('selected')); node.classList.add('selected'); currentId = node.id; currentTab = 'overview'; beep(480); renderPanel(); }}));
        root.addEventListener('click', ev => {{ if(!ev.target.closest('.node') && !ev.target.closest('.panel')){{ currentId = null; root.querySelectorAll('.node').forEach(n => n.classList.remove('selected')); renderPanel(); }} }});
        const flowToggle = root.querySelector('#flowToggle'); const flowRange = root.querySelector('#flowRange'); const flowReadout = root.querySelector('#flowReadout');
        function syncFlow(){{ const v = Number(flowRange.value); const dur = Math.max(2.4, 8.5 - v/18); root.querySelectorAll('.flow').forEach(p => {{ p.style.setProperty('--speed', `${{dur}}s`); p.classList.toggle('off', !flowOn); }}); flowReadout.textContent = `Simulated export: ${{v}}%`; }}
        flowToggle.addEventListener('click', () => {{ flowOn = !flowOn; flowToggle.classList.toggle('off', !flowOn); flowToggle.textContent = `Animated Power Flow: ${{flowOn ? 'On' : 'Off'}}`; beep(720); syncFlow(); }});
        flowRange.addEventListener('input', syncFlow);
        syncFlow();
      </script>
    </div>
    """
    components.html(html, height=height, scrolling=True)
