import json

import streamlit.components.v1 as components


SOLAR_COMPONENTS = {
  'component-pv-modules': {'id':'component-pv-modules','name':'PV Modules','category':'generation','overview':{'description':'PV modules convert sunlight into direct current electricity. At utility scale they define raw energy capture, so soiling, temperature, mismatch, and degradation immediately affect plant yield.','keyFunction':'Generate DC electricity from solar irradiance.','typicalSpec':'580-700 Wp bifacial modules, 1,500 VDC strings.'},'technical':{'voltage':'~35-45 VDC per module, up to 1,500 VDC per string.','current':'Typically 13-18 A short-circuit current per module.','powerRating':'580-700 Wp per module, aggregated to multi-MWdc blocks.','typicalManufacturers':['LONGi','Trina Solar','Jinko Solar','JA Solar'],'connectionUpstream':'Solar resource, tracker structure, earthing, and weather exposure.','connectionDownstream':'DC string cabling and combiner boxes or inverter inputs.','failureModes':['Hot spots','Cell cracking','PID or mismatch','Connector heating','Glass breakage']},'operations':{'inspectionFrequency':'Monthly visual checks plus annual thermography and IV investigations.','commonIssues':['Soiling','Bypass diode issues','Shading mismatch','Delamination','Accelerated degradation'],'performanceMetrics':['Specific yield','PR contribution','String current balance','Degradation rate'],'lifespanYears':'25-35 years','replacementCost':'Medium'},'scada':{'dataPoints':['String current','POA irradiance','Module temperature','Tracker angle'],'kpis':['Array availability','Mismatch loss','Soiling loss','Normalized energy'],'anomalySignals':['Persistent underperforming strings','Thermal outliers','PR drop in clear weather'],'scadaTags':['STR_CURR_*','POA_IRR','MOD_TEMP','ARRAY_AVAIL']}},
  'component-dc-cables': {'id':'component-dc-cables','name':'DC Cables','category':'transmission','overview':{'description':'DC cables collect energy from strings and route it to the combiner or inverter. Installation quality and connector integrity are critical because many latent faults appear first on the DC side.','keyFunction':'Carry string DC power to the aggregation point.','typicalSpec':'1.5 kV PV cable, commonly 4-10 mm2 for string circuits.'},'technical':{'voltage':'Designed for 1,500 VDC systems.','current':'String circuits commonly 13-18 A; higher on aggregated runs.','powerRating':'Rated by ampacity and voltage drop rather than by nameplate power.','typicalManufacturers':['Prysmian','Nexans','Lapp','Top Cable'],'connectionUpstream':'PV module strings.','connectionDownstream':'String combiners or direct inverter inputs.','failureModes':['Insulation damage','Loose connectors','Ground faults','Rodent damage','Reverse polarity wiring']},'operations':{'inspectionFrequency':'Quarterly visual route checks and annual thermal or continuity testing.','commonIssues':['Water ingress','Unsupported loops','Connector mismatch','Voltage drop issues'],'performanceMetrics':['Circuit availability','Ground fault rate','Voltage consistency'],'lifespanYears':'20-30 years','replacementCost':'Low to medium'},'scada':{'dataPoints':['String voltage','String current','Insulation alarms'],'kpis':['DC availability','Current dispersion','Fault recurrence'],'anomalySignals':['Intermittent string loss','Insulation alarms','Large current mismatch'],'scadaTags':['DC_VOLT_*','DC_CURR_*','GROUND_FAULT']}},
  'component-string-combiner': {'id':'component-string-combiner','name':'String Combiner Boxes','category':'protection','overview':{'description':'Combiner boxes merge multiple strings onto fewer outgoing feeders and provide DC fusing, surge protection, and often string-level monitoring. They are a practical isolation point when string behavior diverges.','keyFunction':'Aggregate strings and provide DC protection and monitoring.','typicalSpec':'8-32 inputs, fused, with SPD and monitored output.'},'technical':{'voltage':'1,000-1,500 VDC.','current':'Often 150-400 A aggregated output depending on the block.','powerRating':'Tied to the number of strings feeding each inverter block.','typicalManufacturers':['Weidmuller','Phoenix Contact','Eaton','Mersen'],'connectionUpstream':'Individual PV string circuits.','connectionDownstream':'Main DC feeders to inverter MPPT inputs.','failureModes':['Fuse operation','SPD end-of-life','Water ingress','Loose terminations']},'operations':{'inspectionFrequency':'Quarterly visual checks and annual torque and thermal verification.','commonIssues':['Blown fuses','SPD alarms','Burnt terminals','Seal failure'],'performanceMetrics':['Healthy string count','Current balance','SPD status'],'lifespanYears':'15-25 years','replacementCost':'Medium'},'scada':{'dataPoints':['Per-string current','Output current','Fuse status','SPD status'],'kpis':['Strings online','Mismatch index','Fault isolation speed'],'anomalySignals':['Single-string collapse','Repeated fuse trips','Combiner undercurrent'],'scadaTags':['SCB_STR_CURR_*','SCB_OUT_CURR','SCB_FUSE_ALM']}},
  'component-inverter': {'id':'component-inverter','name':'String / Central Inverter','category':'conversion','overview':{'description':'The inverter converts variable DC from the field into synchronized AC power while performing MPPT, protection, and grid-support functions. It is one of the highest-leverage components in terms of both availability and performance.','keyFunction':'Convert DC to grid-compliant AC power.','typicalSpec':'150-350 kW string inverter or 2.5-5 MW central inverter, 98.5%+ peak efficiency.'},'technical':{'voltage':'DC up to 1,500 V; AC output typically 400-800 VAC.','current':'Usually hundreds of amps on the LV AC side depending on unit size.','powerRating':'From 150 kW string units to 5 MW+ central units.','typicalManufacturers':['Sungrow','Huawei','Power Electronics','SMA'],'connectionUpstream':'Combiner outputs or direct strings.','connectionDownstream':'LV AC feeders to the step-up transformer.','failureModes':['Power stack failure','Fan/filter degradation','Control board faults','Grid trips']},'operations':{'inspectionFrequency':'Daily remote review and semi-annual or annual preventive maintenance.','commonIssues':['Thermal derating','Repeated trips','Firmware issues','Auxiliary power loss'],'performanceMetrics':['Availability','Efficiency','Trip rate','MPPT balance','Clipping hours'],'lifespanYears':'10-15 years','replacementCost':'High'},'scada':{'dataPoints':['DC V/I','AC active/reactive power','Temperature','Alarm codes','Status'],'kpis':['Availability','Efficiency','Specific yield by block','Reactive compliance'],'anomalySignals':['Frequent trip-reset cycles','Persistent underproduction','Temperature-driven derating'],'scadaTags':['INV_P_AC','INV_Q_AC','INV_DC_V','INV_DC_I','INV_ALARM_CODE']}},
  'component-ac-cables-lv': {'id':'component-ac-cables-lv','name':'LV/MV AC Cables','category':'transmission','overview':{'description':'These feeders transfer inverter output to the local step-up transformer. Proper sizing, harmonic duty, and installation discipline matter because small weaknesses can become repeated breaker or thermal issues.','keyFunction':'Carry inverter AC power to the transformer.','typicalSpec':'400-800 VAC feeders sized for thermal and harmonic duty.'},'technical':{'voltage':'Typically 400-800 VAC.','current':'Several hundred amps depending on inverter rating.','powerRating':'Aligned to inverter block power and transformer LV side rating.','typicalManufacturers':['Nexans','Prysmian','General Cable','Top Cable'],'connectionUpstream':'Inverter AC terminals.','connectionDownstream':'MV transformer low-voltage side.','failureModes':['Loose lugs','Insulation breakdown','Joint defects','Water ingress']},'operations':{'inspectionFrequency':'Semi-annual visual and thermal checks plus outage testing as required.','commonIssues':['Hot joints','Phase imbalance','Sheath damage','Incorrect phase rotation'],'performanceMetrics':['Cable loss','Thermal margin','Fault incidence'],'lifespanYears':'20-30 years','replacementCost':'Medium'},'scada':{'dataPoints':['Phase current','Phase voltage','Feeder status'],'kpis':['Phase balance','Cable loading','Loss factor'],'anomalySignals':['Breaker trips','Current asymmetry','Unexpected transformer inlet heating'],'scadaTags':['LV_I_A','LV_I_B','LV_I_C','LV_FEEDER_STATUS']}},
  'component-mv-transformer': {'id':'component-mv-transformer','name':'MV Step-Up Transformer','category':'conversion','overview':{'description':'The block transformer raises inverter output from low voltage to the plant\'s medium-voltage collection network. It is the electrical bridge between conversion equipment and the export path.','keyFunction':'Step LV inverter output up to plant MV level.','typicalSpec':'0.4-0.8 kV to 20-33 kV, usually 2.5-8 MVA.'},'technical':{'voltage':'Typical ratio 690 VAC / 33 kV or similar.','current':'High current on LV, lower current on MV; rated in MVA.','powerRating':'2.5-8 MVA per transformer block.','typicalManufacturers':['Hitachi Energy','Schneider Electric','Siemens Energy','TMC'],'connectionUpstream':'Inverter LV output.','connectionDownstream':'MV switchgear and feeder cable.','failureModes':['Oil leaks','Winding insulation degradation','Bushing failure','Thermal overload']},'operations':{'inspectionFrequency':'Monthly visual checks with annual oil and electrical testing.','commonIssues':['Hot oil alarms','Cooling failures','Leaking gaskets','Protection trips'],'performanceMetrics':['Loading','Top oil temp','Winding temp','Availability'],'lifespanYears':'25-35 years','replacementCost':'High'},'scada':{'dataPoints':['Oil temp','Winding temp','Currents','Protection status'],'kpis':['Loading factor','Thermal aging index','Trip frequency'],'anomalySignals':['Rising temperature at constant load','Gas alarms','Unbalanced current'],'scadaTags':['XFMR_TOP_OIL_TEMP','XFMR_WDG_TEMP','XFMR_MVA','XFMR_TRIP']}},
  'component-mv-switchgear': {'id':'component-mv-switchgear','name':'MV Switchgear','category':'protection','overview':{'description':'MV switchgear provides switching, isolation, and protection between PV feeder transformers, the BESS branch, and the collection bus. It is the operational control point used to sectionalize faults and manage outages.','keyFunction':'Switch and protect the MV feeders and shared bus.','typicalSpec':'20-33 kV switchgear with vacuum breakers and protection relays.'},'technical':{'voltage':'20-33 kV collection bus.','current':'Common feeder ratings 630-2,500 A.','powerRating':'Rated by voltage, current, and fault duty.','typicalManufacturers':['Schneider Electric','ABB','Siemens','Ormazabal'],'connectionUpstream':'PV and BESS feeder transformers.','connectionDownstream':'MV collection network and substation bus.','failureModes':['Breaker mechanism failure','Relay misoperation','Arc damage','Interlock faults']},'operations':{'inspectionFrequency':'Monthly checks with periodic relay and breaker maintenance.','commonIssues':['Loss of control power','Stored-energy wear','Door interlock defects'],'performanceMetrics':['Feeder uptime','Breaker operation count','Fault clearing time'],'lifespanYears':'20-30 years','replacementCost':'High'},'scada':{'dataPoints':['Breaker status','Trip cause','Bus voltage','Feeder current'],'kpis':['Protection availability','Selectivity success','Breaker health'],'anomalySignals':['Repeat feeder trips','Slow operations','Protection alarms without obvious external fault'],'scadaTags':['MV_BRK_STATUS','MV_TRIP_CAUSE','MV_BUS_V','MV_FEEDER_I']}},
  'component-mv-cables': {'id':'component-mv-cables','name':'MV Collection Cables','category':'transmission','overview':{'description':'The MV collection network moves aggregated feeder power to the substation. Because it is usually underground, failures are less visible and often more disruptive to isolate and repair.','keyFunction':'Carry MV power from distributed blocks to the substation.','typicalSpec':'12-36 kV XLPE underground collection circuits.'},'technical':{'voltage':'Commonly 20-33 kV.','current':'Depends on feeder aggregation and soil thermal conditions.','powerRating':'Driven by conductor size and feeder topology.','typicalManufacturers':['Prysmian','Nexans','NKT','Elsewedy'],'connectionUpstream':'MV switchgear outgoing feeders.','connectionDownstream':'Substation incomers.','failureModes':['Joint failure','Insulation puncture','Sheath damage','Water treeing']},'operations':{'inspectionFrequency':'Route checks after civils and periodic testing during outages.','commonIssues':['Joint overheating','Moisture ingress','Damaged route marking'],'performanceMetrics':['Feeder losses','Fault rate per km','Cable health index'],'lifespanYears':'25-40 years','replacementCost':'High'},'scada':{'dataPoints':['Feeder current','Voltage drop','Fault indications'],'kpis':['Network availability','Loss factor','Fault localization time'],'anomalySignals':['Unexplained feeder trips','Voltage depression','Intermittent insulation alarms'],'scadaTags':['MV_FEEDER_LOAD','MV_ROUTE_FAULT','MV_VDROP']}},
  'component-hv-transformer': {'id':'component-hv-transformer','name':'HV Main Transformer','category':'conversion','overview':{'description':'The main transformer raises plant MV to the utility export voltage and is a central high-value asset. All export typically passes through it before reaching the point of common coupling.','keyFunction':'Step plant MV up to HV export level.','typicalSpec':'20-33 kV to 63-225 kV, tens to hundreds of MVA.'},'technical':{'voltage':'Primary 20-33 kV; secondary often 63, 90, 132, or 225 kV.','current':'Rated in MVA with lower current on the HV side.','powerRating':'Typically 40-250 MVA.','typicalManufacturers':['Hitachi Energy','GE Vernova','Siemens Energy','Hyosung'],'connectionUpstream':'MV switchgear or substation MV bus.','connectionDownstream':'HV yard and PCC.','failureModes':['Insulation aging','Cooling failure','Bushing flashover','Differential trips']},'operations':{'inspectionFrequency':'Continuous remote supervision with annual DGA and electrical tests.','commonIssues':['Cooling bank outages','Oil seepage','Contaminated bushings','Abnormal DGA'],'performanceMetrics':['Export availability','Thermal loading','DGA trend health'],'lifespanYears':'30-40 years','replacementCost':'High'},'scada':{'dataPoints':['Oil temp','Winding temp','Tap position','Currents','Protection states'],'kpis':['Availability','Thermal aging rate','Forced outage risk'],'anomalySignals':['Rising gas content','Unexpected tap movement','Top-oil rise without load increase'],'scadaTags':['GSU_TOP_OIL','GSU_WDG_TEMP','GSU_TAP_POS','GSU_DIFF_TRIP']}},
  'component-substation': {'id':'component-substation','name':'HV Substation','category':'transmission','overview':{'description':'The substation consolidates transformation, protection, metering, control, and switching before export. It is the place where plant electrical behavior becomes visible to the utility operator.','keyFunction':'Host the export bus, switching, metering, and grid interface controls.','typicalSpec':'AIS or GIS yard with utility relays, station auxiliaries, and telecontrol.'},'technical':{'voltage':'Matches the utility connection level and the plant MV level internally.','current':'Defined by plant export capacity and fault studies.','powerRating':'Full plant export capability plus duty margin.','typicalManufacturers':['Hitachi Energy','Schneider Electric','Siemens Energy','GE Vernova'],'connectionUpstream':'MV collection system and main transformer.','connectionDownstream':'Transmission or distribution utility line.','failureModes':['Auxiliary supply failure','Breaker defects','Protection miscoordination','Metering chain faults']},'operations':{'inspectionFrequency':'Daily remote supervision and periodic yard and relay maintenance.','commonIssues':['Battery charger alarms','Protection comms loss','Yard contamination'],'performanceMetrics':['Export availability','Compliance events','Breaker operations'],'lifespanYears':'30+ years','replacementCost':'High'},'scada':{'dataPoints':['Bus voltage','Export current','Breaker positions','Relay events'],'kpis':['Substation availability','Trip cause resolution time','Compliance'],'anomalySignals':['Unexpected protection blocks','Telemetry loss to grid operator','Repeated breaker alarms'],'scadaTags':['SUB_BUS_V','SUB_EXPORT_MW','SUB_BREAKER_STATUS','SUB_RELAY_EVENT']}},
  'component-grid-connection': {'id':'component-grid-connection','name':'Grid Connection Point (PCC)','category':'transmission','overview':{'description':'The PCC is the contractual and electrical interface between the plant and the public grid. Revenue metering and grid-code compliance are anchored here.','keyFunction':'Define the export interface with the utility network.','typicalSpec':'Revenue metering, power quality supervision, intertrip and dispatch interface.'},'technical':{'voltage':'Same as utility interconnection level.','current':'Driven by export capacity and network conditions.','powerRating':'Full contracted import/export capability.','typicalManufacturers':['Landis+Gyr','Schneider Electric','Siemens','Secure Meters'],'connectionUpstream':'HV substation outgoing bay.','connectionDownstream':'Utility feeder or transmission line.','failureModes':['Meter discrepancy','Power quality non-compliance','Dispatch signal loss']},'operations':{'inspectionFrequency':'Continuous supervision with periodic calibration and utility witness testing.','commonIssues':['Reactive power non-compliance','Curtailment mismatch','Meter communications faults'],'performanceMetrics':['Export MWh','Availability at PCC','Reactive compliance'],'lifespanYears':'20-30 years','replacementCost':'Medium to high'},'scada':{'dataPoints':['Revenue energy','P/Q export','Voltage','Frequency','Curtailment setpoint'],'kpis':['Grid code compliance','Curtailment impact','Export availability'],'anomalySignals':['Mismatch between plant and revenue meter','Unexpected clipping or curtailment','Frequency excursions'],'scadaTags':['PCC_MW','PCC_MVAR','PCC_KWH','PCC_FREQ','CURTAIL_SETPOINT']}},
  'component-bess-batteries': {'id':'component-bess-batteries','name':'BESS Battery Racks','category':'storage','overview':{'description':'Battery racks store energy for shifting, ramp control, and ancillary services. Their state of health and thermal behavior determine how much usable energy remains available over time.','keyFunction':'Store electrical energy for later dispatch.','typicalSpec':'Containerized LFP or NMC systems, 3.2-3.7 V per cell, hundreds of kWh per rack string.'},'technical':{'voltage':'Cell 3.2-3.7 V; container bus often 700-1,500 VDC.','current':'High bidirectional DC current depending on C-rate.','powerRating':'Typically paired to 1-4 hour system duration at MW scale.','typicalManufacturers':['CATL','BYD','Tesla','Fluence'],'connectionUpstream':'BMS, HVAC, fire suppression, and DC battery bus.','connectionDownstream':'PCS DC inputs.','failureModes':['Cell imbalance','Cooling failure','SOC drift','Thermal runaway precursor alarms']},'operations':{'inspectionFrequency':'Continuous BMS monitoring with monthly physical inspections.','commonIssues':['Rack imbalance','HVAC faults','Reduced usable energy','BMS comms loss'],'performanceMetrics':['SOC','SOH','Round-trip efficiency','Cycle count','Temperature spread'],'lifespanYears':'10-20 years','replacementCost':'High'},'scada':{'dataPoints':['SOC','SOH','Cell temperatures','Rack voltage','BMS alarms'],'kpis':['Available energy','Cycle count','Thermal uniformity','Degradation rate'],'anomalySignals':['Diverging rack voltages','Fast temperature rise','Repeated HVAC alarms'],'scadaTags':['BESS_SOC','BESS_SOH','BESS_CELL_TEMP_MAX','BMS_ALARM_CODE']}},
  'component-bess-pcs': {'id':'component-bess-pcs','name':'BESS Power Conversion System (PCS)','category':'conversion','overview':{'description':'The PCS is the bidirectional inverter that charges and discharges the battery system while supporting voltage and reactive power control. It converts stored energy into dispatchable AC power.','keyFunction':'Convert battery DC to AC and AC back to DC under dispatch control.','typicalSpec':'1-5 MW bidirectional converter with four-quadrant capability.'},'technical':{'voltage':'DC bus often 900-1,500 V; AC side typically 400-690 VAC.','current':'High bidirectional current on both DC and AC interfaces.','powerRating':'1-5 MW per PCS block is common.','typicalManufacturers':['Sungrow','Power Electronics','SMA','Gamesa Electric'],'connectionUpstream':'Battery racks and DC bus.','connectionDownstream':'BESS transformer and MV switchgear.','failureModes':['Power electronics failure','Cooling derating','Control instability','Grid-code trips']},'operations':{'inspectionFrequency':'Daily remote review and annual OEM maintenance.','commonIssues':['Missed dispatch setpoints','Harmonic alarms','Cooling issues','EMS comms mismatch'],'performanceMetrics':['Availability','Response time','Efficiency','Command tracking error'],'lifespanYears':'10-15 years','replacementCost':'High'},'scada':{'dataPoints':['Charge/discharge MW','Reactive power','DC V/I','Alarm codes','Dispatch mode'],'kpis':['Response latency','Conversion efficiency','Availability'],'anomalySignals':['Unexpected idle state','Grid faults','High harmonic alarms','Missed commands'],'scadaTags':['PCS_P_CMD','PCS_P_ACT','PCS_Q_ACT','PCS_MODE','PCS_ALARM']}},
  'component-bess-transformer': {'id':'component-bess-transformer','name':'BESS Transformer','category':'conversion','overview':{'description':'The BESS transformer steps the PCS output to the shared MV bus. It lets storage connect to the same collection architecture as the PV field while remaining operationally distinct.','keyFunction':'Step PCS output to the plant MV collection voltage.','typicalSpec':'0.4-0.69 kV to 20-33 kV, sized to PCS block rating.'},'technical':{'voltage':'Typically 400-690 VAC / 20-33 kV.','current':'Bidirectional thermal duty driven by dispatch cycles.','powerRating':'1-5 MVA per PCS block.','typicalManufacturers':['Hitachi Energy','Schneider Electric','TMC','Efacec'],'connectionUpstream':'PCS output panel.','connectionDownstream':'MV switchgear shared with PV collection.','failureModes':['Thermal overload','Insulation wear','Cooling issues','Protection trips']},'operations':{'inspectionFrequency':'Monthly visual checks and annual electrical testing.','commonIssues':['Thermal cycling stress','Cooling fan faults','Loose connections'],'performanceMetrics':['Loading profile','Temperature profile','Availability'],'lifespanYears':'20-30 years','replacementCost':'High'},'scada':{'dataPoints':['Temperature','Current','Protection status','Cooling alarms'],'kpis':['BESS export path availability','Thermal stress','Trip frequency'],'anomalySignals':['High temperature at moderate dispatch','Overcurrent relay events'],'scadaTags':['BESS_XFMR_TEMP','BESS_XFMR_I','BESS_XFMR_TRIP']}},
  'component-monitoring-scada': {'id':'component-monitoring-scada','name':'SCADA / Monitoring System','category':'monitoring','overview':{'description':'The SCADA layer acquires data, stores events, distributes alarms, and gives operators a unified view of the plant. It turns dispersed equipment behavior into actionable operational decisions.','keyFunction':'Centralize monitoring, alarming, dispatch, and reporting.','typicalSpec':'Plant historian, gateway, PLC/RTU, OEM interfaces, and remote dashboards.'},'technical':{'voltage':'Low-voltage controls and communication infrastructure.','current':'Not power-critical; driven by auxiliaries and network devices.','powerRating':'Usually station auxiliary loads only.','typicalManufacturers':['Power Factors','Meteocontrol','Schneider Electric','Siemens'],'connectionUpstream':'Field devices, relays, meters, weather stations, inverters, BMS/EMS.','connectionDownstream':'Operators, historians, analytics platforms, and utility telemetry.','failureModes':['Gateway outage','Time sync drift','Comms loss','Bad data mapping']},'operations':{'inspectionFrequency':'Continuous use with routine alarm rationalization and backup testing.','commonIssues':['Telemetry gaps','Tag scaling errors','Time offset','User access misconfiguration'],'performanceMetrics':['Data completeness','Alarm latency','System uptime'],'lifespanYears':'8-15 years','replacementCost':'Medium'},'scada':{'dataPoints':['All plant telemetry, statuses, alarms, events, setpoints'],'kpis':['Data quality','Alarm response time','Fleet availability'],'anomalySignals':['Frozen tags','Flatlined sensors','Clock drift','Communication loss'],'scadaTags':['SITE_MW','SITE_PR','COMM_HEALTH','ALARM_ACTIVE_COUNT']}},
  'component-weather-station': {'id':'component-weather-station','name':'Weather Station / Pyranometers','category':'monitoring','overview':{'description':'Weather stations provide the reference measurements needed to normalize plant output and diagnose underperformance. Without trusted irradiance and temperature data, PR and loss attribution become far less reliable.','keyFunction':'Measure irradiance and ambient conditions for performance assessment.','typicalSpec':'GHI and POA pyranometers, back-of-module temperature, wind speed and direction.'},'technical':{'voltage':'Low-voltage sensor and logger supply.','current':'Minimal instrumentation loads.','powerRating':'Instrumentation only.','typicalManufacturers':['Kipp & Zonen','Hukseflux','Vaisala','Campbell Scientific'],'connectionUpstream':'Meteorological exposure and mounting structures.','connectionDownstream':'SCADA historian, PPC, tracker control, and analytics.','failureModes':['Sensor drift','Soiling','Leveling errors','Heater failure','Cable damage']},'operations':{'inspectionFrequency':'Weekly cleanliness checks and periodic calibration.','commonIssues':['Dirty pyranometers','Tilt drift','Failed aspirated temperature probes'],'performanceMetrics':['Sensor availability','Calibration drift','Data plausibility'],'lifespanYears':'8-15 years','replacementCost':'Low to medium'},'scada':{'dataPoints':['GHI','POA','Ambient temperature','Module temperature','Wind speed'],'kpis':['Reference irradiance uptime','Clear-sky deviation','Sensor bias'],'anomalySignals':['Irradiance inconsistent with neighboring sensors','Flatlined temperature','Sudden offset after maintenance'],'scadaTags':['MET_GHI','MET_POA','MET_T_AMB','MET_T_MOD','MET_WIND']}},
  'component-tracker-system': {'id':'component-tracker-system','name':'Single-Axis Tracker System','category':'generation','overview':{'description':'Single-axis trackers rotate module tables to improve irradiance capture across the day while using backtracking to limit row-to-row shading. Their performance influences both energy yield and mechanical reliability.','keyFunction':'Orient PV rows to optimize irradiance capture and reduce shading losses.','typicalSpec':'Single-axis rows with motor drives, local controllers, and backtracking logic.'},'technical':{'voltage':'Typically low-voltage DC or AC motor supply.','current':'Driven by distributed tracker motors and controllers.','powerRating':'Auxiliary mechanical load rather than major electrical export equipment.','typicalManufacturers':['Nextracker','Array Technologies','PVHardware','GameChange Solar'],'connectionUpstream':'SCADA/PPC setpoints, weather conditions, site topography.','connectionDownstream':'PV module orientation and generation profile.','failureModes':['Stuck rows','Motor failures','Controller comms loss','Wind stow issues']},'operations':{'inspectionFrequency':'Weekly remote fault review and periodic mechanical inspection.','commonIssues':['Misalignment','Bearing wear','Limit switch issues','Backtracking misconfiguration'],'performanceMetrics':['Tracker availability','Stow response','Row angle accuracy'],'lifespanYears':'20-30 years','replacementCost':'Medium'},'scada':{'dataPoints':['Row angle','Mode','Wind stow status','Motor current','Fault code'],'kpis':['Tracker availability','Angle error','Stow event success'],'anomalySignals':['Persistent row angle offset','High motor current','Rows not returning from stow'],'scadaTags':['TRK_ANGLE','TRK_MODE','TRK_STOW','TRK_FAULT']}},
  'component-grounding-system': {'id':'component-grounding-system','name':'Grounding / Earthing System','category':'protection','overview':{'description':'The earthing system keeps touch and step voltages within safe limits and provides a fault return path for equipment protection. It also underpins lightning protection and EMC performance across the plant.','keyFunction':'Provide personnel safety, lightning protection, and fault current return paths.','typicalSpec':'Buried earth grid, equipment bonds, and lightning down conductors.'},'technical':{'voltage':'Designed around fault and lightning transients rather than steady-state voltage.','current':'Carries fault and surge currents for short durations.','powerRating':'Not rated by continuous export power.','typicalManufacturers':['nVent ERICO','OBO Bettermann','DEHN','Furse'],'connectionUpstream':'All metallic structures and electrical enclosures.','connectionDownstream':'Site earth grid, electrodes, and protective devices.','failureModes':['Corrosion','Broken bonds','High earth resistance','Lightning damage']},'operations':{'inspectionFrequency':'Annual inspection with periodic continuity and resistance testing.','commonIssues':['Loose bonds','Corroded lugs','Damaged lightning air terminals'],'performanceMetrics':['Earth resistance','Bond continuity','Lightning event inspections'],'lifespanYears':'25-40 years','replacementCost':'Low to medium'},'scada':{'dataPoints':['Insulation alarms','Ground fault alarms','Lightning counter pulses'],'kpis':['Ground fault incidence','Earthing test trend'],'anomalySignals':['Repeated insulation faults','Localized surge damage after storms'],'scadaTags':['GROUND_FAULT','INSULATION_ALARM','LIGHTNING_COUNT']}}
}


def _solar_panels(cols: int = 7, rows: int = 3, arrays: int = 3,
                   pw: int = 54, ph: int = 15, cg: int = 6, rg: int = 8,
                   ag: int = 22, ox: int = 20, oy: int = 24) -> str:
    """Generate a clean rectangular panel grid for the SVG farm scene."""
    parts: list[str] = []
    for a in range(arrays):
        ay = oy + a * (rows * (ph + rg) - rg + ag)
        for r in range(rows):
            ry = ay + r * (ph + rg)
            for c in range(cols):
                cx = ox + c * (pw + cg)
                parts.append(
                    f"<rect class='solar' x='{cx}' y='{ry}' "
                    f"width='{pw}' height='{ph}' rx='2'/>"
                )
                # subtle horizontal cell divider for a realistic panel look
                my = ry + ph // 2
                parts.append(
                    f"<line stroke='#8BBFD4' stroke-width='0.6' "
                    f"x1='{cx + 3}' y1='{my}' x2='{cx + pw - 3}' y2='{my}' "
                    f"opacity='.32'/>"
                )
    return "".join(parts)


def render_solar_farm_explorer(site_name: str | None = None, height: int = 1750) -> None:
    title = site_name or "Utility-Scale Solar PV + BESS Explorer"
    data = json.dumps(SOLAR_COMPONENTS)
    html = f"""
    <div id='sf-root'>
      <style>
        :root{{--bg:#FAFAF7;--panel:#FFFDF9;--ink:#2D2D2D;--navy:#1B2A4A;--copper:#D4864A;--forest:#2E7D5B;--gold:#E8B84B;--muted:#8A9AAF;--sky:#EAF1F4;--land:#D4E6A8;--road:#7E8594;--cream:#F3EEE3;--line:#4D5E74;--shadow:0 22px 44px rgba(27,42,74,.12);--radius:28px;--mono:'JetBrains Mono','IBM Plex Mono',Consolas,monospace;--serif:'DM Serif Display','Libre Baskerville',Georgia,serif;--sans:'Source Sans 3','DM Sans','Segoe UI',sans-serif;}}
        *{{box-sizing:border-box}} body{{margin:0;background:var(--bg);font-family:var(--sans);color:var(--ink)}}
        .shell{{display:flex;gap:24px;align-items:flex-start;padding:24px;background:var(--bg)}}
        .stage{{flex:1 1 62%;background:var(--panel);border:1px solid rgba(27,42,74,.08);border-radius:var(--radius);box-shadow:var(--shadow);padding:24px;min-width:0}}
        .panel{{flex:1 1 38%;position:sticky;top:16px;background:var(--panel);border:1px solid rgba(27,42,74,.08);border-radius:var(--radius);box-shadow:var(--shadow);padding:24px;min-height:760px}}
        .eyebrow{{letter-spacing:.18em;text-transform:uppercase;font-size:11px;color:var(--copper);font-weight:700;margin-bottom:8px}}
        h1,h2,h3{{font-family:var(--serif);margin:0}} h1{{font-size:32px;line-height:1.05;color:var(--navy)}} h2{{font-size:25px;color:var(--navy)}} h3{{font-size:17px;color:var(--navy)}}
        .lede{{color:#526070;max-width:72ch;font-size:16px;line-height:1.58;margin:14px 0 18px}}
        .controls{{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin-bottom:16px;padding:14px 16px;border-radius:18px;background:linear-gradient(180deg,#F7F3EC 0%,#F1ECE2 100%);border:1px solid rgba(27,42,74,.08)}}
        .chip,.tab{{border:1px solid rgba(27,42,74,.12);background:#fff;border-radius:999px;padding:8px 12px;font:600 13px var(--sans);color:var(--navy)}}
        .tab.active{{background:var(--navy);color:#fff;border-color:var(--navy)}}
        .toggle{{border:none;background:var(--navy);color:#fff;border-radius:999px;padding:10px 14px;font:700 13px var(--sans);cursor:pointer;transition:background .24s ease,transform .24s ease}}
        .toggle.off{{background:#8A9AAF}} .toggle:hover{{transform:translateY(-1px)}}
        .metric{{margin-left:auto;display:flex;gap:10px;align-items:center;color:#5D687A;font-size:13px}} input[type=range]{{accent-color:var(--copper)}}
        .legend{{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0 0}} .legend span{{font-size:12px;color:#5F6C7C;padding:6px 10px;border-radius:999px;background:#F6F4EE;border:1px solid rgba(27,42,74,.08)}}
        svg{{width:100%;height:auto;border-radius:22px;background:linear-gradient(180deg,var(--sky) 0%,#F4F7EE 42%,#EEF4E3 100%);border:1px solid rgba(27,42,74,.08)}}
        .label{{font:700 15px var(--sans);fill:var(--navy);letter-spacing:.02em}} .sub{{font:500 11px var(--sans);fill:#607089}}
        .road{{fill:none;stroke:var(--road);stroke-width:52;stroke-linecap:round;stroke-linejoin:round}} .road-mid{{fill:none;stroke:#EAE6D9;stroke-width:3.4;stroke-dasharray:16 12;stroke-linecap:round}}
        .cable{{fill:none;stroke-width:8;stroke-linecap:round;stroke-linejoin:round}} .dc{{stroke:#B56D41}} .ac{{stroke:#2E7D5B}} .aux{{stroke:#A7B3C0;stroke-width:4;stroke-dasharray:10 10}}
        .energy{{fill:var(--gold);filter:drop-shadow(0 0 6px rgba(232,184,75,.45));opacity:.95}} .energy.off{{opacity:.16}}
        .node > *{{transition:fill .22s ease,stroke .22s ease,transform .22s ease,opacity .22s ease}} .node .hit{{fill:transparent;stroke:transparent;stroke-width:18}}
        .node .surface{{fill:#F7F3EC;stroke:var(--line);stroke-width:2}} .node .metal{{fill:#D8E0D2;stroke:var(--line);stroke-width:1.6}} .node .building{{fill:#E5D6C2;stroke:var(--line);stroke-width:1.6}}
        .node .solar{{fill:url(#panelGrad);stroke:var(--line);stroke-width:1.5}} .node .outline{{fill:none;stroke:var(--line);stroke-width:1.6}}
        .node:hover .surface,.node:hover .metal,.node:hover .building{{fill:#F0D9BF;cursor:pointer}} .node.selected .surface,.node.selected .metal,.node.selected .building{{fill:#E8B84B;stroke:#D4864A}} .node.selected .outline,.node.selected .solar{{stroke:#D4864A}}
        .panel.hidden .detail-wrap{{display:none}} .placeholder{{display:grid;place-items:center;height:100%;min-height:620px;color:#667588;text-align:left}}
        .pill{{display:inline-flex;align-items:center;gap:8px;background:#F5EFE8;color:var(--copper);border:1px solid rgba(212,134,74,.22);padding:7px 10px;border-radius:999px;font:700 11px var(--sans);letter-spacing:.12em;text-transform:uppercase}}
        .spec{{margin:18px 0 0;padding:16px;border-radius:18px;background:#F7F4EE;border:1px solid rgba(27,42,74,.08)}} .spec div{{font:600 13px var(--mono);color:#4B5970}}
        .tabs{{display:flex;flex-wrap:wrap;gap:8px;margin:18px 0}} .content p,.content li{{font-size:15px;line-height:1.6;color:#49596E}} .content ul{{padding-left:20px;margin:8px 0 0}}
        .kv{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:16px}} .card{{background:#F7F4EE;border:1px solid rgba(27,42,74,.08);border-radius:18px;padding:14px}} .card small{{display:block;color:#7A8798;text-transform:uppercase;letter-spacing:.08em;font-size:11px;margin-bottom:8px}} .card strong{{display:block;color:#1B2A4A;font:700 15px var(--mono);line-height:1.45}}
        @media (max-width:980px){{.shell{{flex-direction:column;padding:14px}} .panel{{position:relative;top:0;min-height:auto}} .metric{{margin-left:0;width:100%}} h1{{font-size:26px}}}}
      </style>
      <div class='shell'>
        <section class='stage'>
          <div class='eyebrow'>Interactive Asset Anatomy</div>
          <h1>{title}</h1>
          <p class='lede'>A more visual utility-scale plant scene inspired by isometric site diagrams. Click the arrays, power conversion equipment, substation yard, or battery containers to inspect how the PV and BESS architecture works end to end.</p>
          <div class='controls'>
            <button id='flowToggle' class='toggle'>Energy Motion: On</button>
            <label class='chip'>Plant loading <input id='flowRange' type='range' min='0' max='100' value='72'></label>
            <div class='metric'><span id='flowReadout'>Simulated export: 72%</span></div>
          </div>
          <svg viewBox='0 0 1480 980' role='img' aria-label='Illustrated solar farm and battery storage layout'>
            <defs>
              <linearGradient id='panelGrad' x1='0' y1='0' x2='1' y2='1'><stop offset='0%' stop-color='#5F82A8'/><stop offset='100%' stop-color='#243B55'/></linearGradient>
              <linearGradient id='fieldGrad' x1='0' y1='0' x2='0' y2='1'><stop offset='0%' stop-color='#DDEEAF'/><stop offset='100%' stop-color='#CBE197'/></linearGradient>
              <linearGradient id='farmBg' x1='0' y1='0' x2='0' y2='1'><stop offset='0%' stop-color='#C8D89A'/><stop offset='100%' stop-color='#B8CC84'/></linearGradient>
            </defs>
            <circle cx='180' cy='92' r='52' fill='#F1C95B' opacity='.92'/>
            <g opacity='.6'><ellipse cx='1194' cy='84' rx='74' ry='22' fill='#FFFFFF'/><ellipse cx='1250' cy='82' rx='52' ry='18' fill='#FFFFFF'/></g>
            <path d='M0 342 C248 284 420 368 678 344 C924 322 1120 246 1480 304 L1480 980 L0 980 Z' fill='url(#fieldGrad)'/>
            <path class='road' d='M0 214 C182 214 402 182 642 152 C906 118 1186 112 1480 134'/><path class='road-mid' d='M0 214 C182 214 402 182 642 152 C906 118 1186 112 1480 134'/>
            <path class='road' d='M0 864 C230 758 462 714 728 744 C980 772 1244 640 1480 480'/><path class='road-mid' d='M0 864 C230 758 462 714 728 744 C980 772 1244 640 1480 480'/>
            <path class='cable dc' d='M556 418 C564 416 570 416 582 418'/><path class='cable dc' d='M718 420 C724 420 726 422 734 428'/><path class='cable dc' d='M852 436 C862 446 870 480 878 498'/><path class='cable ac' d='M982 590 C1090 588 1176 574 1260 536'/><path class='cable ac' d='M1260 536 C1320 506 1380 438 1418 370'/><path class='cable ac' d='M1046 760 C1120 706 1182 640 1238 558'/><path class='cable dc' d='M800 828 C850 774 894 704 936 638'/><path class='cable aux' d='M178 226 C420 198 760 190 1092 222 C1222 234 1310 250 1382 288'/><path class='cable aux' d='M212 658 C400 702 598 766 800 830'/>
            <circle id='orb-pv-1' class='energy' r='8' cx='556' cy='418'/><circle id='orb-pv-2' class='energy' r='8' cx='852' cy='436'/><circle id='orb-pv-3' class='energy' r='8' cx='982' cy='590'/><circle id='orb-pv-4' class='energy' r='8' cx='1260' cy='536'/><circle id='orb-bess-1' class='energy' r='8' cx='800' cy='828'/><circle id='orb-bess-2' class='energy' r='8' cx='936' cy='638'/><circle id='orb-bess-3' class='energy' r='8' cx='1046' cy='760'/>
            <text x='82' y='56' class='label'>Visual Plant Scene</text><text x='82' y='76' class='sub'>PV field, storage branch, substation yard, and grid export shown as one connected site</text>
            <g id='component-weather-station' class='node' data-component-type='monitoring' transform='translate(130 118)'><circle class='hit' cx='42' cy='52' r='58'/><line class='outline' x1='40' y1='12' x2='40' y2='88'/><circle class='surface' cx='40' cy='14' r='15'/><path class='building' d='M42 34 L70 48 L70 58 L42 50 Z'/><line class='outline' x1='40' y1='60' x2='76' y2='82'/><text x='-6' y='118' class='label'>Weather Station</text></g>
            <g id='component-monitoring-scada' class='node' data-component-type='monitoring' transform='translate(1180 184)'><rect class='hit' x='-12' y='-10' width='210' height='120' rx='26'/><rect class='building' x='0' y='0' width='188' height='92' rx='18'/><rect class='surface' x='16' y='18' width='84' height='34' rx='8'/><rect class='surface' x='112' y='18' width='50' height='34' rx='8'/><line class='outline' x1='18' y1='64' x2='164' y2='64'/><text x='0' y='118' class='label'>SCADA &amp; Monitoring</text></g>
            <g id='component-pv-modules' class='node' data-component-type='generation' transform='translate(26 265)'>
              <rect class='hit' x='-18' y='-14' width='566' height='300' rx='28'/>
              <rect fill='url(#farmBg)' stroke='#7A9C42' stroke-width='1.8' x='0' y='0' width='530' height='250' rx='10' opacity='.6'/>
              {_solar_panels(cols=8, rows=3, arrays=3, pw=54, ph=14, cg=6, rg=7, ag=20, ox=22, oy=22)}
              <text x='0' y='266' class='label'>PV Modules</text>
              <text x='0' y='282' class='sub'>Rows of bifacial panels on tracker tables</text>
            </g>
            <g id='component-tracker-system' class='node' data-component-type='generation' transform='translate(26 582)'>
              <rect class='hit' x='-20' y='-10' width='338' height='106' rx='22'/>
              <line class='outline' x1='22' y1='56' x2='22' y2='14'/>
              <line class='outline' x1='100' y1='56' x2='100' y2='14'/>
              <line class='outline' x1='178' y1='56' x2='178' y2='14'/>
              <line class='outline' x1='256' y1='56' x2='256' y2='14'/>
              <rect class='solar' x='2' y='6' width='40' height='16' rx='2' transform='rotate(-14 22 14)'/>
              <rect class='solar' x='80' y='6' width='40' height='16' rx='2' transform='rotate(-14 100 14)'/>
              <rect class='solar' x='158' y='6' width='40' height='16' rx='2' transform='rotate(-14 178 14)'/>
              <rect class='solar' x='236' y='6' width='40' height='16' rx='2' transform='rotate(-14 256 14)'/>
              <text x='0' y='92' class='label'>Tracker System</text>
            </g>
            <g id='component-dc-cables' class='node' data-component-type='transmission' transform='translate(582 392)'><rect class='hit' x='-18' y='-22' width='154' height='82' rx='22'/><path class='outline' d='M0 10 C36 -10 54 24 88 4 C108 -8 126 12 136 -6'/><path class='building' d='M0 28 C36 8 54 42 88 22 C108 10 126 30 136 12'/><text x='0' y='76' class='label'>DC Cabling</text></g>
            <g id='component-string-combiner' class='node' data-component-type='protection' transform='translate(734 392)'><rect class='hit' x='-10' y='-10' width='128' height='118' rx='22'/><rect class='surface' x='0' y='0' width='106' height='88' rx='16'/><rect class='building' x='18' y='16' width='70' height='26' rx='6'/><line class='outline' x1='53' y1='42' x2='53' y2='68'/><line class='outline' x1='34' y1='68' x2='72' y2='68'/><text x='-6' y='112' class='label'>String Combiner</text></g>
            <g id='component-inverter' class='node' data-component-type='conversion' transform='translate(888 520)'><rect class='hit' x='-10' y='-10' width='118' height='132' rx='22'/><rect class='surface' x='0' y='0' width='100' height='106' rx='18'/><rect class='building' x='18' y='18' width='64' height='28' rx='7'/><path class='outline' d='M18 74 L34 60 L46 74 L60 58 L74 74'/><text x='0' y='128' class='label'>Inverter</text></g>
            <g id='component-ac-cables-lv' class='node' data-component-type='transmission' transform='translate(1006 554)'><rect class='hit' x='-10' y='-10' width='170' height='76' rx='22'/><path class='outline' d='M0 22 L32 8 L66 24 L98 10 L132 26'/><path class='building' d='M0 38 L32 24 L66 40 L98 26 L132 42'/><text x='0' y='80' class='label'>LV AC Feeders</text></g>
            <g id='component-mv-transformer' class='node' data-component-type='conversion' transform='translate(1200 500)'><rect class='hit' x='-14' y='-10' width='132' height='126' rx='24'/><rect class='surface' x='0' y='0' width='104' height='98' rx='18'/><circle class='building' cx='40' cy='46' r='16'/><circle class='building' cx='68' cy='46' r='16'/><text x='-2' y='122' class='label'>MV Transformer</text></g>
            <g id='component-mv-switchgear' class='node' data-component-type='protection' transform='translate(1236 658)'><rect class='hit' x='-10' y='-10' width='108' height='134' rx='22'/><rect class='surface' x='0' y='0' width='84' height='106' rx='14'/><rect class='building' x='24' y='18' width='34' height='56' rx='6'/><line class='outline' x1='42' y1='76' x2='42' y2='94'/><text x='-2' y='128' class='label'>MV Switchgear</text></g>
            <g id='component-mv-cables' class='node' data-component-type='transmission' transform='translate(1318 520)'><rect class='hit' x='-10' y='-10' width='146' height='86' rx='24'/><path class='outline' d='M0 22 C30 2 42 42 74 18 C98 0 122 30 136 10'/><path class='building' d='M0 40 C30 20 42 60 74 36 C98 18 122 48 136 28'/><text x='0' y='88' class='label'>MV Collection</text></g>
            <g id='component-bess-batteries' class='node' data-component-type='storage' transform='translate(620 764)'><rect class='hit' x='-14' y='-10' width='198' height='98' rx='24'/><rect class='building' x='0' y='0' width='180' height='72' rx='14'/><rect class='surface' x='16' y='18' width='38' height='34' rx='5'/><rect class='surface' x='68' y='18' width='38' height='34' rx='5'/><rect class='surface' x='120' y='18' width='38' height='34' rx='5'/><text x='0' y='96' class='label'>BESS Batteries</text></g>
            <g id='component-bess-pcs' class='node' data-component-type='conversion' transform='translate(830 760)'><rect class='hit' x='-10' y='-10' width='124' height='122' rx='22'/><rect class='surface' x='0' y='0' width='102' height='92' rx='18'/><rect class='building' x='18' y='18' width='66' height='24' rx='6'/><path class='outline' d='M18 62 L34 48 L48 62 L60 48 L74 62'/><text x='0' y='116' class='label'>BESS PCS</text></g>
            <g id='component-bess-transformer' class='node' data-component-type='conversion' transform='translate(968 748)'><rect class='hit' x='-10' y='-10' width='122' height='118' rx='22'/><rect class='surface' x='0' y='0' width='98' height='88' rx='16'/><circle class='building' cx='36' cy='42' r='14'/><circle class='building' cx='62' cy='42' r='14'/><text x='0' y='112' class='label'>BESS Transformer</text></g>
            <g id='component-hv-transformer' class='node' data-component-type='conversion' transform='translate(1288 324)'><rect class='hit' x='-12' y='-10' width='164' height='122' rx='24'/><rect class='surface' x='0' y='0' width='138' height='94' rx='18'/><circle class='building' cx='52' cy='44' r='20'/><circle class='building' cx='84' cy='44' r='20'/><text x='0' y='118' class='label'>HV Transformer</text></g>
            <g id='component-substation' class='node' data-component-type='transmission' transform='translate(1340 198)'><rect class='hit' x='-16' y='-12' width='136' height='138' rx='24'/><rect class='surface' x='0' y='0' width='108' height='102' rx='16'/><rect class='building' x='18' y='22' width='14' height='42' rx='4'/><rect class='building' x='48' y='16' width='14' height='50' rx='4'/><rect class='building' x='78' y='28' width='14' height='36' rx='4'/><line class='outline' x1='18' y1='76' x2='92' y2='76'/><text x='0' y='122' class='label'>Substation Yard</text></g>
            <g id='component-grid-connection' class='node' data-component-type='transmission' transform='translate(1290 96)'><rect class='hit' x='-10' y='-10' width='178' height='86' rx='24'/><polygon class='surface' points='0,34 30,12 30,26 110,26 110,42 30,42 30,56'/><line class='outline' x1='110' y1='34' x2='152' y2='34'/><text x='0' y='88' class='label'>Grid Connection</text></g>
            <g id='component-grounding-system' class='node' data-component-type='protection' transform='translate(1108 860)'><rect class='hit' x='-10' y='-10' width='242' height='90' rx='24'/><line class='outline' x1='86' y1='6' x2='86' y2='34'/><line class='outline' x1='54' y1='34' x2='118' y2='34'/><line class='outline' x1='62' y1='48' x2='110' y2='48'/><line class='outline' x1='70' y1='62' x2='102' y2='62'/><text x='0' y='16' class='label'>Grounding / Earthing</text><text x='0' y='38' class='sub'>Common fault path, touch-voltage control, lightning protection</text></g>
            <g id='service-truck-top' transform='translate(1040 126)'><rect x='0' y='0' width='52' height='22' rx='6' fill='#F1EFE4' stroke='#4D5E74' stroke-width='1.5'/><rect x='38' y='4' width='24' height='18' rx='4' fill='#BFCFE1' stroke='#4D5E74' stroke-width='1.5'/><circle cx='14' cy='24' r='5' fill='#354152'/><circle cx='46' cy='24' r='5' fill='#354152'/></g>
            <g id='service-van-bottom' transform='translate(120 808)'><rect x='0' y='0' width='58' height='24' rx='7' fill='#80B84E' stroke='#4D5E74' stroke-width='1.5'/><path d='M44 0 L60 0 L68 12 L68 24 L44 24 Z' fill='#A9D170' stroke='#4D5E74' stroke-width='1.5'/><circle cx='16' cy='26' r='5' fill='#354152'/><circle cx='50' cy='26' r='5' fill='#354152'/></g>
          </svg>
          <div class='legend'><span>Generation</span><span>Conversion</span><span>Transmission</span><span>Storage</span><span>Monitoring</span><span>Protection</span></div>
        </section>
        <aside id='panel' class='panel hidden'>
          <div class='placeholder' id='placeholder'><div><div class='eyebrow'>Selection</div><h2>Choose a plant component</h2><p class='lede' style='margin-top:12px'>This version is more like a premium site map. Click the illustrated equipment to see what it does, what to monitor, and how it sits in the power chain.</p></div></div>
          <div class='detail-wrap' id='detail'></div>
        </aside>
      </div>
      <script>
        const data = {data};
        const root = document.getElementById('sf-root');
        const panel = root.querySelector('#panel');
        const detail = root.querySelector('#detail');
        const placeholder = root.querySelector('#placeholder');
        const tabs = ['overview','technical','operations','scada'];
        const pvTrack = [[336,468],[676,598],[982,590],[1260,536],[1418,370]];
        const bessTrack = [[800,828],[936,638],[1046,760],[1238,558]];
        const topRoad = [[1040,126],[1140,122],[1260,122],[1380,128]];
        const bottomRoad = [[120,808],[320,724],[564,716],[840,754],[1140,690],[1360,552]];
        const orbs = {{ pv:[document.getElementById('orb-pv-1'),document.getElementById('orb-pv-2'),document.getElementById('orb-pv-3'),document.getElementById('orb-pv-4')], bess:[document.getElementById('orb-bess-1'),document.getElementById('orb-bess-2'),document.getElementById('orb-bess-3')] }};
        const truckTop = document.getElementById('service-truck-top');
        const vanBottom = document.getElementById('service-van-bottom');
        const iconMap = {{ generation:'Field capture', conversion:'Electrical conversion', transmission:'Network transfer', storage:'Energy shifting', monitoring:'Operations visibility', protection:'Protection and safety' }};
        let currentId = null; let currentTab = 'overview'; let flowOn = true; let tick = 0; let speed = 0.72;
        function list(items){{ return `<ul>${{(items||[]).map(x => `<li>${{x}}</li>`).join('')}}</ul>`; }}
        function panelMarkup(c){{
          if(currentTab==='overview') return `<p>${{c.overview.description}}</p><div class='spec'><div>${{c.overview.keyFunction}}</div><div>${{c.overview.typicalSpec}}</div></div><div class='kv'><div class='card'><small>Category</small><strong>${{c.category}}</strong></div><div class='card'><small>Role</small><strong>${{iconMap[c.category]}}</strong></div></div>`;
          if(currentTab==='technical') return `<div class='kv'><div class='card'><small>Voltage</small><strong>${{c.technical.voltage}}</strong></div><div class='card'><small>Current</small><strong>${{c.technical.current}}</strong></div><div class='card'><small>Power Rating</small><strong>${{c.technical.powerRating}}</strong></div><div class='card'><small>Typical OEMs</small><strong>${{c.technical.typicalManufacturers.join(', ')}}</strong></div></div><p><strong>Upstream:</strong> ${{c.technical.connectionUpstream}}</p><p><strong>Downstream:</strong> ${{c.technical.connectionDownstream}}</p><h3>Failure Modes</h3>${{list(c.technical.failureModes)}}`;
          if(currentTab==='operations') return `<div class='kv'><div class='card'><small>Inspection Frequency</small><strong>${{c.operations.inspectionFrequency}}</strong></div><div class='card'><small>Lifespan</small><strong>${{c.operations.lifespanYears}}</strong></div><div class='card'><small>Replacement Cost</small><strong>${{c.operations.replacementCost}}</strong></div><div class='card'><small>Performance Metrics</small><strong>${{c.operations.performanceMetrics.join(', ')}}</strong></div></div><h3>Common Issues</h3>${{list(c.operations.commonIssues)}}`;
          return `<div class='kv'><div class='card'><small>Typical Data</small><strong>${{c.scada.dataPoints.join(', ')}}</strong></div><div class='card'><small>KPIs</small><strong>${{c.scada.kpis.join(', ')}}</strong></div></div><h3>Key SCADA Tags</h3>${{list(c.scada.scadaTags)}}<h3>Anomaly Signals</h3>${{list(c.scada.anomalySignals)}}`;
        }}
        function beep(freq){{ try{{ const ctx = new (window.AudioContext||window.webkitAudioContext)(); const osc = ctx.createOscillator(); const gain = ctx.createGain(); osc.type='sine'; osc.frequency.value=freq; gain.gain.value=.012; osc.connect(gain); gain.connect(ctx.destination); osc.start(); osc.stop(ctx.currentTime + .05); }}catch(e){{}} }}
        function renderPanel(){{
          if(!currentId){{ panel.classList.add('hidden'); placeholder.style.display='grid'; detail.innerHTML=''; return; }}
          const c = data[currentId];
          panel.classList.remove('hidden');
          placeholder.style.display='none';
          detail.innerHTML = `<div class='pill'>${{c.category}}</div><h2 style='margin-top:14px'>${{c.name}}</h2><p class='lede' style='margin:10px 0 0'>${{c.overview.description}}</p><div class='tabs'>${{tabs.map(t => `<button class="tab ${{currentTab===t?'active':''}}" data-tab="${{t}}">${{t==='scada'?'Data & SCADA':t==='operations'?'O&M Considerations':t.charAt(0).toUpperCase()+t.slice(1)}}</button>`).join('')}}</div><div class='content'>${{panelMarkup(c)}}</div>`;
          detail.querySelectorAll('.tab').forEach(btn => btn.addEventListener('click', () => {{ currentTab = btn.dataset.tab; beep(620); renderPanel(); }}));
        }}
        function setSelected(id){{ currentId = id; currentTab = 'overview'; root.querySelectorAll('.node').forEach(n => n.classList.toggle('selected', n.id===id)); beep(460); renderPanel(); }}
        root.querySelectorAll('.node').forEach(node => node.addEventListener('click', ev => {{ ev.stopPropagation(); setSelected(node.id); }}));
        root.addEventListener('click', ev => {{ if(!ev.target.closest('.node') && !ev.target.closest('.panel')){{ currentId = null; root.querySelectorAll('.node').forEach(n => n.classList.remove('selected')); renderPanel(); }} }});
        function point(track, progress){{
          const segs = track.length - 1;
          const scaled = Math.max(0, Math.min(segs - 0.0001, progress * segs));
          const idx = Math.floor(scaled);
          const local = scaled - idx;
          const a = track[idx];
          const b = track[idx + 1];
          return [a[0] + (b[0]-a[0]) * local, a[1] + (b[1]-a[1]) * local];
        }}
        function angle(track, progress){{
          const segs = track.length - 1;
          const scaled = Math.max(0, Math.min(segs - 0.0001, progress * segs));
          const idx = Math.floor(scaled);
          const a = track[idx];
          const b = track[idx + 1];
          return Math.atan2(b[1]-a[1], b[0]-a[0]) * 180 / Math.PI;
        }}
        function moveOrbs(track, elems, base, drift){{
          elems.forEach((el, i) => {{
            if(!el) return;
            el.classList.toggle('off', !flowOn);
            const p = (base + i * drift) % 1;
            const xy = point(track, p);
            el.setAttribute('cx', xy[0].toFixed(1));
            el.setAttribute('cy', xy[1].toFixed(1));
          }});
        }}
        function moveVehicle(el, track, progress){{
          if(!el) return;
          const xy = point(track, progress);
          const ang = angle(track, progress);
          el.setAttribute('transform', `translate(${{xy[0].toFixed(1)}} ${{xy[1].toFixed(1)}}) rotate(${{ang.toFixed(1)}})`);
        }}
        function syncFlow(){{
          const v = Number(flowRange.value);
          speed = Math.max(0.18, v / 100);
          flowReadout.textContent = `Simulated export: ${{v}}%`;
          flowToggle.textContent = `Energy Motion: ${{flowOn ? 'On' : 'Off'}}`;
          flowToggle.classList.toggle('off', !flowOn);
          [...orbs.pv, ...orbs.bess].forEach(el => el && el.classList.toggle('off', !flowOn));
        }}
        function animate(){{
          tick += speed * 0.006;
          moveOrbs(pvTrack, orbs.pv, tick % 1, 0.18);
          moveOrbs(bessTrack, orbs.bess, (1 - tick * 0.8) % 1, 0.22);
          moveVehicle(truckTop, topRoad, (tick * 0.18) % 1);
          moveVehicle(vanBottom, bottomRoad, (tick * 0.24) % 1);
          requestAnimationFrame(animate);
        }}
        const flowToggle = root.querySelector('#flowToggle');
        const flowRange = root.querySelector('#flowRange');
        const flowReadout = root.querySelector('#flowReadout');
        flowToggle.addEventListener('click', () => {{ flowOn = !flowOn; beep(720); syncFlow(); }});
        flowRange.addEventListener('input', syncFlow);
        syncFlow();
        animate();
      </script>
    </div>
    """
    components.html(html, height=height, scrolling=True)
